### ISSUE TITLE
[BUG] Custom memo needs more characters

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1006]
**Describe the bug**
At the moment it is not possible to include enough bytes in the `custom memo` for `deposit` to register Thornames/Mayanames correctly.
Please increase that full memo `~:ac-test:ETH:0x6621d872f17109d6601c49edba526ebcfd332d5d:thor1dl7un46w7l7f3ewrnrm6nq58nerjtp0dradjtd:ETH.USDC-0XA0B86991C6218B36C1D19D4A2E9EB0CE3606EB48` can be included.

-v44

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/1011
