### ISSUE TITLE
[BUG] - Possible to recover the wallet without the password

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-ios#1016]
I saved my wallet with a password, exported it, and then, when importing, I could import without my password.

**Comment by johnnyluo** [comment]
Just double checked , I can't reproduce it.
is it on MacOS? Ios?

**Comment by realpaaao** [comment]
Just checked on iOS. Also can't reproduce

**Comment by enriquesouza** [comment]
It had a bug on mac os where I could not save it with a password. I believe it was fixed in this current version.
