### ISSUE TITLE
CoinStore Refactory

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-ios#1022]
We need to change the coin store so it can be easier to add tokens.

We should add only the token address;

This new style overcomplicated it 

```
static var blastBAG: CoinMeta {
            CoinMeta(chain: Chain.blast, ticker: "BAG", logo: "bag", decimals: 18, priceProviderId: "", contractAddress: "0xb9dfCd4CF589bB8090569cb52FaC1b88Dbe4981F", isNativeToken: false)
        }
```
        
So, instead, we should add only the native tokens there.

Example:

```

static var ethereum: CoinMeta {
            CoinMeta(chain: Chain.ethereum, ticker: "ETH", logo: "eth", decimals: 18, priceProviderId: "ethereum", contractAddress: "", isNativeToken: true,

tokens: ["0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", "0xdac17f958d2ee523a2206206994597c13d831ec7", ....]
            
            
            )
        }
``` 
        
        All the token info should come from the API.

**Comment by flypaper0** [comment]
We can, but it will require us to add extra API fetch on initial load or on showing token selection list. 
What this change can improve in current app work? @enriquesouza

**Comment by enriquesouza** [comment]
We already fetch the tokens from 1 inch, so to avoid decimals errors, images, etc., we should always retrieve them dynamically. It would also make the Token store cleaner, which will help avoid errors and only leave native tokens on the Token store.
