### ISSUE TITLE
[BUG] Address book/camera on custom token search

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1027]
**Describe the bug**
The address book and camera are able to insert a saved address on the custom token add. Please remove both and just have pasting addresses.

**Screenshots**
![image](https://github.com/user-attachments/assets/f1554147-0fad-4d3e-8b92-7b169343daf4)

-v45

**Comment by realpaaao** [comment]
![IMG_7942.png](https://github.com/user-attachments/assets/8754de19-52d8-4b91-b2d1-f4937c107b03)

@Rockindash some user also reported text cut off on that screen, can you check and fix?

**Comment by Rockindash** [comment]
Sure, will fix that today.

**Comment by Rockindash** [comment]
Fixed the issue in the following PR:
https://github.com/vultisig/vultisig-ios/pull/1037
