### ISSUE TITLE
[BUG] QR invoice scan not correct

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1047]
**Describe the bug**
When scanning an Invoice QR code with camera the app doesn't behave well:
1. It doesn't select the correct chain or asset when scanning from `main view ` or `send view`
2. When an amount is included in the QR the camera on `main view` doesn't register it but on `send view` it does

**To Reproduce**
1. Scan QR Code with camera on main screen or send screen
2. See error

**Expected behavior**
The App correctly selects the chain, asset and if included price

**Screenshots**
Invoice QR
![image](https://github.com/user-attachments/assets/6e318aea-ef59-4384-8024-e2566df0cc57)

Invoice QR with amount
![image](https://github.com/user-attachments/assets/9675ba53-6f5e-477d-913e-7b5ca6e091bb)

-v46

**Comment by johnnyluo** [comment]
for the second QR code ,  maybe just extract address from it
