### ISSUE TITLE
[BUG] Keysign signed bad button description

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1056]
**Describe the bug**
When signing a tx the pairing device displays "Done" on the continue Button

**Expected behavior**
Be congruent with the initating device and display "Complete"

**Screenshots**
![image](https://github.com/user-attachments/assets/7729cc0a-a909-44ae-87fd-3be8e8ab7f45)

-v47

**Comment by johnnyluo** [comment]
closing , as it has been fixed
