### ISSUE TITLE
IMPROVE: Update Label for RUNEPool Withdraw

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1059]
The label for the amount to withdraw on RUNEPool Withdrawal is little confusing.

Please update the Label `Basis Points` to `Percentage`, so the user can withdraw a percentage of his RUNEPool and knows exactly how much percent.

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/81c4f9a7-c5fe-413c-acdb-00567a56ac6a">

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/1088
