### ISSUE TITLE
[BUG] Wrong swap error for RUNE-ETH route

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1099]
**Describe the bug**
If amount of RUNE is too low to swap it prompts `swap route not available` instead of not sufficient amount error

**Expected behavior**
Please display correct error

**Screenshots**
<img width="998" alt="image" src="https://github.com/user-attachments/assets/adc5fcff-67e4-4a70-ad1d-4dfc77db0ac1">

-v48

**Comment by flypaper0** [comment]
@realpaaao Happened on vary small amount when amount lower than fee. TC do not return recommended amount. 

Error: 
```
failed to simulate swap: fail to add outbound tx: 2 errors occurred:\n\t* internal error\n\t* not enough asset to pay for fees\n\n [gitlab.com/thorchain/thornode/x/thorchain/errors.go:73]
```

If you increase value a little then you'll get recommended amount error. 

If value higher then recommended amount swaps works as expected: 

<img width=300 src="https://github.com/user-attachments/assets/aa9924f3-4fb6-478f-be11-ce5573f929e6">

**Comment by flypaper0** [comment]
@realpaaao please reopen issue if you have any suggestions

**Comment by realpaaao** [comment]
@flypaper0 could we display the error "failed to simulate because amount to small" or something? That user knows that value is to small?
