### ISSUE TITLE
[ADD] Update onboarding flow

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1112]
**Is your feature request related to a problem? Please describe.**
Update onboarding flow to match Figma

**Additional context**
[Add any other context or screenshots about the feature request here.](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=11079-34847&t=6FOglR9t4MlThKkY-1)

**Comment by johnnyluo** [comment]
closing , not relevant anymore
