### ISSUE TITLE
[ADD] FastVault UI/UX update

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1118]
To add to #1117 please update the UI/UX according to [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=9327-20194&t=zic6Ejv3RRtmzdlA-1).

If `FastVault` or `SecureVault` is selected please prompt the user the new "FastVault flow" where the VultiServer is included and the e-mail, password, passcode and move to QR code afterwards.

If `SecureVault` is selected please prompt the old onboarding flow where only the user devices are included.

**Comment by johnnyluo** [comment]
closing , this one is done as part of #1143
