### ISSUE TITLE
[Update] Verify screen to include signing with Vultisigner

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1127]
Check and adjust the [verify signing screen](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=3901-10923&t=1e4a9AnmbCdNRxIJ-1) if the Vault setup is a:
1. Fast Vault = Display only "Fast sign" button
2. Active Vault = Display "Fast sign" and "Paired Sign" buttons
3. Secure Vault = Only dispay "Paired sign" button as main button design

according to figma:
![image](https://github.com/user-attachments/assets/4c3ec5d6-a3cd-4418-b7ff-cf106ae9a276)

**Comment by johnnyluo** [comment]
already implemented with #1143
