### ISSUE TITLE
[BUG] Change deposit verify view, basis points label to percentace

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1131]
**Describe the bug**
When verifying a message deposit for removing from the RUNEPool, it shows `Basis Points` but should be labled `Percentage`

**Expected behavior**
Show label as `Percentage`

**Screenshots**
![image](https://github.com/user-attachments/assets/30264282-0e6e-4f53-b610-d12fe6ae9669)

-v50

**Comment by johnnyluo** [comment]
THORChain is always working with BasisPoint , so instead we should change the label
