### ISSUE TITLE
[ADD]: Part-assigned Vaults

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#1132]
# Context

Vult shares are hard to reason about, we should think about the UX around them.
People may confuse vault shares and get stuck, thinking they are backed up. 

- [ ] Part-assigned generation
- [ ] Vult Share Exports have Part
- [ ] Part Labels

# Desired

Use the concept of parts to help users visually identify them. Each vault share is assigned a part, which is in the name as well as label.

# Rules

## New vaults
1) Starting device is always `part1`
2) Assign the next parts in order of joining session
3) Vault Part can never be re-assigned. 

## Reshare: 
1) Starting device is new `part1`
2) Assign the next parts in order of joining session

<img width="424" alt="image" src="https://github.com/user-attachments/assets/786d1143-2265-4454-a50f-8c9403706586">

**Comment by johnnyluo** [comment]
discussion happens https://discord.com/channels/1203844257220395078/1282301697967788134

**Comment by SxMShaDoW** [comment]
I wonder if adding colors as a secondary indicator could be useful. With that being said - colors run into a "color blind" scenario - so we would probably run out of colors for N of N but if it wasn't a main indicator (where parts is) could still be useful. Just my random 2 cents.
