### ISSUE TITLE
[ADD]: Fast Sign Label

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#1135]
1) Do an API check to VultiServer does vult exist, and not the same share
2) if yes, add this label
3) for both Fast/Active vaults

<img width="718" alt="image" src="https://github.com/user-attachments/assets/12d8eaa0-75fd-404a-a926-f0ab4db39e6e">

**Comment by johnnyluo** [comment]
Go through `signers` of vault , if one signer has name start with `Server-` , then it is a fastvault
