### ISSUE TITLE
BUG: UNBOND Thorchain/MAYA sends amount

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1142]
**Describe the bug**
Currently when unbonding on Thorchain or Maya the Rune tx amount sent with the memo is the same as the unbonding amount in the memo. This leads to  needs to be `0` 

**Expected behavior**
The actual Rune amount sent with such a unbonding memo needs to be `0`.
The unbonding amount is specified in the memo itself. 
Please refer to thorchain docs [here](https://dev.thorchain.org/concepts/memos.html#bond-unbond-and-leave) and [here](https://docs.thorchain.org/thornodes/leaving#unbonding)

**Additional context**
This leads to the user loosing the amount sent with the tx to the node and it is very difficult to retrieve as it is currently treated as rewards. Making it very hard to retrieve the funds.

**Comment by johnnyluo** [comment]
fixed in #1144
