### ISSUE TITLE
[UPDATE] Reshare flow to include Vultiserver

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1148]
Currently the Reshare flow does not seperate between including Vultiserver or not.
Leading to that the server always joins. 

Please implement/update Reshare flow according to [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=12051-8148&t=biwQdjGi8xPSNTNa-4) so user can have an optional Vultiserver on reshare.

Also include logic to check if the vault already has a vault share on the vultisig server or a new one needs to be created.

**Comment by johnnyluo** [comment]
This one has been implemented , and merged , @realpaaao can you please do some QA for it?

**Comment by flypaper0** [comment]
closed with https://github.com/vultisig/vultisig-ios/pull/1218
