### ISSUE TITLE
[UPDATE] Create or Import Vault View

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1149]
To get rid of one view, we want to update the `create a vault or import a vault view`.

Please only display this view on the first onboarding according to [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=1123-11923&t=biwQdjGi8xPSNTNa-4) flow:
![image](https://github.com/user-attachments/assets/deba01c8-8114-4d24-b4ad-5f427d78343a)
afterwards promt this view:
![image](https://github.com/user-attachments/assets/f4a0f33b-937e-47fb-9639-ca49c6b55236)

If user wants to create a second or further vaults let them go over `vault select view` to select it directly over the updated `setup view `, (please also update buttons on this view) :
![image](https://github.com/user-attachments/assets/e33c8c77-229d-405d-abb5-d56bf864d2d0)

This will make it possible to get rid of one screen and improving user experience.

**Comment by johnnyluo** [comment]
why we make "Import Vault" a small button?

**Comment by realpaaao** [comment]
@johnnyluo yes, not the best. we updated onboarding flow and therefore also got rid of this page, issue #1152 will resolve also this issue.

**Comment by johnnyluo** [comment]
Closing in favor of #1152
