### ISSUE TITLE
[UPDATE] Onboarding/Vault creation to completely include Fast Vaults

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1152]
Fast Vault introduced some big changes on how the flow on vault creation works. 
We optimized the flow, removed screens/views.

Therefore please check [figma onboarding flow](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=9327-20194&t=lLoyGkUT4G1Tb1lk-4) and update the app accordingly to match the flow.

Figma should be clear on how the flow works, if there are questions please ping me.

**Comment by realpaaao** [comment]
This will also fix #1112

**Comment by johnnyluo** [comment]
this one is implemented closing
