### ISSUE TITLE
[UPDATE] Send flow to include Fast vaults

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1153]
Please verify and if needed adjust the flow of sending to implement to ensure a good UX with fast faults and active vaults.

Especially when signing with `fast sign` that it directly goes to signing the tx without showing the QR code.

See [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=15130-30956&t=XMCoUJ9gy6xyabXt-4) for verification and reference.

Let me know if questions arise in regards to the figma flow.

**Comment by johnnyluo** [comment]
fixed #1201
