### ISSUE TITLE
[ADD]: Grouped Rows for Vaults (folders)

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#1203]
1) Edit Vault -> "ADD FOLDER" button on bottom
2) Move Vaults into Folders
3) Rename Folders

<img width="369" alt="image" src="https://github.com/user-attachments/assets/e49fbf88-8259-4cf8-9e33-83f284e22a6d">

**Comment by realpaaao** [comment]
will be closed with #1233

**Comment by johnnyluo** [comment]
closing , in favor of 1233
