### ISSUE TITLE
[BUG] Not able to select chains on macOS

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1207]
**Describe the bug**
After selecting chains on macOS and changing view to `main view`, it is not possible to go into chain selection again until terminating app.

**To Reproduce**
1. Go to `chain selection`
2. Select/deselect chains
3. go back to `main view`
4. try enter chain selection again
5. See error

**Expected behavior**
able to enter `chain selection `normally

**Screenshots**
<img width="898" alt="image" src="https://github.com/user-attachments/assets/3d26b9e8-7c4a-4988-aae6-a9ef8bbf69e7">

mac OS on v 1.1

**Comment by johnnyluo** [comment]
This is an issue only happens on MacOS 15 Sequoia

**Comment by johnnyluo** [comment]
Fixed in #1211
