### ISSUE TITLE
[BUG] Signing SUI tx not possible

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1209]
**Describe the bug**
Signing a SUI tx is currently not possible.

**To Reproduce**
1. send SUI
2. sign SUI tx

**Expected behavior**
Able to sign SUI tx

![image](https://github.com/user-attachments/assets/ce4d4cbc-046b-4957-8e56-ccdba4973166)

v1.1

**Comment by enriquesouza** [comment]
Can we have the address of the user?

**Comment by enriquesouza** [comment]
https://suiscan.xyz/mainnet/tx/8WrjPacQQX5H3DXCgLLM99MPBqcpGDHdvbyW3k897jDA

![image](https://github.com/user-attachments/assets/36212c16-b4d2-473a-b5c1-421ac7dbc5fe)

**Comment by realpaaao** [comment]
After talking with @enriquesouza looks like it is related to older wallets.

**Comment by realpaaao** [comment]
QA done. thank you @enriquesouza !
