### ISSUE TITLE
[UPDATE] keygen and sign QR code share png

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1215]
To update and improve the standard of our QR codes for keysign and keygen, please match the design on [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=16691-43962&t=7ZLQREHKs8pCl9oT-4).
Include the padding and description updates.

**Comment by realpaaao** [comment]
@Rockindash on `main` it still does not look like in figma, I see that my description may not have been accurate. Please update the pairing views accordingly.:
![Image](https://github.com/user-attachments/assets/6a68b460-4d66-4821-8d44-0e0c767a3da6)

**Comment by realpaaao** [comment]
@Rockindash please check

**Comment by Rockindash** [comment]
Hey @realpaaao this issue required the update to the QR share images. 
For the pair view itself, they were fixed in the following PR:
https://github.com/vultisig/vultisig-ios/pull/1420
