### ISSUE TITLE
[BUG] Wrong icon/action on address book address

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1216]
**Describe the bug**
When adding a address to `address book` change the `image` icon to a `camera` icon.

**Expected behavior**
Have camera Icon to scan address QR according to [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=4743-6859&t=3qz0md6ak1bNhbTY-1)

**Screenshots**
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/7a2ad1ea-9c6b-4696-acd3-89647a21ed36">

-v1.1

**Comment by johnnyluo** [comment]
This had been fixed

**Comment by realpaaao** [comment]
QA done.
