### ISSUE TITLE
[BUG] MAX button for SUI not working properly

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1223]
**Describe the bug**
When using MAX button for SUI it will not select the max amount but something in between.

**To Reproduce**
1. Go to SUI chain
2. Send tx
3. click `max` on amount

**Expected behavior**
properly insert max amount

**Screenshots**
https://github.com/user-attachments/assets/c9c75a79-06d0-4822-b473-4fa6d04483f1

-v1.1

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/1411

**Comment by realpaaao** [comment]
QA done. 
@enriquesouza You think we can improve that in the furture that no amount will be left ?
