### ISSUE TITLE
[ADD] macOS webcam QR import

### ISSUE THREAD

**Issue by 0xdef1cafe** [vultisig/vultisig-ios#1234]
**Describe the bug**

**please note** - this was the iOS version installed on macOS via the App Store, not the `.pkg` installer

macOS doesn't support/show camera for pairing

**To Reproduce**

1. Fresh install of application on macOS
2. Click `Create a New Vault`
3. Click `ACTIVE`
4. Click `Pair`

**Expected behavior**
I expect to be able to scan the QR code using a webcam

**Screenshots**
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/76c6870c-45c8-4363-977a-6a319c694512">

System:

 - Device: <img width="168" alt="image" src="https://github.com/user-attachments/assets/d20be7a8-fd26-4ce6-8cf0-3d0aafe0e907">
 - OS: macOS Sequoia 15.0 (24A335)
 - Browser n/a
 - Version n/a

**Additional context**

**Comment by realpaaao** [comment]
for the .pkg the `Pair` button is not working at all

**Comment by realpaaao** [comment]
QA done.
