### ISSUE TITLE
[BUG] iOS - active vault labelled as fast vault

### ISSUE THREAD

**Issue by 0xdef1cafe** [vultisig/vultisig-ios#1235]
**Describe the bug**

**please note** - this was the iOS version installed on macOS via the App Store, not the `.pkg` installer
Active fault setup is labelled as fast vault 

**To Reproduce**
follow video below (see end of video)

**Expected behavior**

- [ ] active fault is labelled as active fault, not fast vault

**Screenshots**

https://github.com/user-attachments/assets/69918638-c0c6-4832-acc5-22d2d7a1d7cf

System:

 - Device: iPhone 15 Pro
 - OS: iOS 18.0
 - Browser n/a
 - Version Vultisig Version 1.1

**Additional context**

**Comment by realpaaao** [comment]
QA done.
