### ISSUE TITLE
[BUG] Too many requests on RPC error on SOL

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1237]
**Describe the bug**
Occasionally getting the `Too many requests for a specific RPC call` when sending SOL on the initiating device

**Expected behavior**
have tx hash displayed consistently

**Screenshots**
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/95a54b05-e75b-4b6d-8c77-3f5daf17d58f">

**Comment by johnnyluo** [comment]
closing
