### ISSUE TITLE
[BUG] Secure vault: bad selection logic on creation

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1238]
**Describe the bug**
When creating a `secure vault` and pairing a third device, it automatically deselects the first paired device.
Running into the possibility that user wants to create a `2-3` or bigger vault but just creates a `2-2` vault.

**To Reproduce**
1. create a secure vault
2. add first device
3. add second device

**Expected behavior**
Keep the first device selected if adding further devices.

**Screenshots**
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/03db93e6-c706-4112-83e5-0ad001808054">

-v1.1

**Comment by johnnyluo** [comment]
Fixed in #1240

**Comment by realpaaao** [comment]
QA done.
