### ISSUE TITLE
[BUG] Scanning EVM QR does not open correct chain

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1242]
**Describe the bug**
If any EVM chain QR gets scanned with camera it does not open the respective chain

**Expected behavior**
If BSC QR gets scanned, open BNB send

**Additional context**
Technically does not make a difference but for UX we want to pass this information in our QR so user has the requested EVM chain already selected

**Comment by johnnyluo** [comment]
This is nice to have , and in many cases , we are not able to do it. All EVM based chains share the same address , L1, L2
