### ISSUE TITLE
[BUG] Keygen/keysign with iPad not working

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1257]
**Describe the bug**
It is sometimes not possible to do any keygen or keysign with iPad until restart.
When it happens it never can be discovered, not as initating nor can join as pairing device.

**Expected behavior**
No need to restart the device to be able to use Vultisig again

**Screenshots**

System:

 - Device: iPad
 - OS: iPadOS 17.6
 - Version 1.1.1

**Additional context**
I could not pin down when exactly it happens but when it happens the device needs to be restarted. I noticed it happened on my iPad without the latest version. I will observe further but other users reported the same problem

**Comment by johnnyluo** [comment]
I am going to close this one , as I use iPad to test it all the time , and can't reproduce it
