### ISSUE TITLE
[BUG] Not able to drag an drop backups into macOS

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1267]
**Describe the bug**
It is not possible to drag-and-drop backup files into the app to import on the `import` view

**Expected behavior**
Able to drag and drop

**Screenshots**
![Image](https://github.com/user-attachments/assets/c0d432ff-89b3-42b1-b0ba-b2bcbf809fda)

System:

 - Device: macOS
 - Version 1.1.1

**Comment by johnnyluo** [comment]
on IOS app , when open .vult file , it doesn't open import vault view

**Comment by Rockindash** [comment]
@johnnyluo created a follow-up issue for the same.
https://github.com/vultisig/vultisig-ios/issues/1514

**Comment by realpaaao** [comment]
@Rockindash somehow .dat and .bak files are not possible to import via drag-and drop.
