### ISSUE TITLE
[ADD] Airdrop UI

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1275]
Reason: To have the user get to the airdrop registration we need to implement the UI on mobile.

Instructions: 

- [ ] Add new collum `Register your vault` according to [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=17879-66594&t=wZbOQQSiCqGVYY6K-4)
![Image](https://github.com/user-attachments/assets/13f0cd92-dc20-494f-8e3b-d643dab8d153)

- [ ] When selecting this collum open new [screen](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=17879-66552&t=wZbOQQSiCqGVYY6K-4)
- [ ] Have Vault QR code icon in top right to directly access QR code
- [ ] have `Vultisig Web` linking to `https://web.vultisig.com/` when selected

![Image](https://github.com/user-attachments/assets/5bf2ce5d-a3ae-46c6-a91f-767ecf970ccd)

**Comment by realpaaao** [comment]
@Rockindash I updated the view like we discussed:

![Image](https://github.com/user-attachments/assets/c74c90bb-4c7a-4596-ae00-fe3e48af50be)

**Comment by johnnyluo** [comment]
fixed in #1311

**Comment by realpaaao** [comment]
@Rockindash could you add the Save button as in figma. like we discussed already?

**Comment by realpaaao** [comment]
QA will be done with merging #1326. cc @Rockindash

**Comment by realpaaao** [comment]
QA done.
