### ISSUE TITLE
[BUG] ETH.ARB intrinsic gas too low

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1289]
**Describe the bug**
It is not possible to send ETH.ARB as intrinsic gas set is too low

**Expected behavior**
Able to send ETH.ARB

**Screenshots**
![Image](https://github.com/user-attachments/assets/789343c2-37b9-4b7c-98d2-2b98b51f8830)

 - Version 1.1.2

**Comment by johnnyluo** [comment]
We allow user to set the gas using advance gas limit now , so closing it 
This might cause by a gas spike
