### ISSUE TITLE
[BUG] No password check when resharing with Vultiserver

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1292]
**Describe the bug**
The password check does not happen when resharing with the Vultiserver included. 
It just advances  and can't encounter the Server.

**To Reproduce**
1. Go to Reshare
2. Click on `Reshare with Vultiserver`
3. Do not enter password

**Expected behavior**
Proper password check gets done.

 - Version 1.2.1

**Comment by johnnyluo** [comment]
Fixed in #1324

**Comment by realpaaao** [comment]
QA done.

**Comment by realpaaao** [comment]
QA done.
