### ISSUE TITLE
[BUG] macOS app not starting

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1306]
**Describe the bug**
Many users report that the latest macOS version is not bootable and is stuck on starting up.
See [Discord](https://discord.com/channels/1203844257220395078/1229771263644274822/1293008328833892473)

**Screenshots**
![Image](https://github.com/user-attachments/assets/19521dc2-6cb3-4ac1-bab5-effbdf6c23f1)

System:
various macbook Pros

**Additional context**
Personally don't have that issue but seems to be affecting quite some people

**Comment by johnnyluo** [comment]
this one had been fixed on #1308

**Comment by realpaaao** [comment]
QA not possible. Users report it should be fixed
