### ISSUE TITLE
[BUG] USDT to CACAO swap

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1317]
**Describe the bug**
Not possible to swap USDT to CACAO as the transaction only approves the USDT but does not send it.
Sending a second swap does not mine the tx.

**Expected behavior**
Able to swap USDT to CACAO

**Screenshots**
![Image](https://github.com/user-attachments/assets/2737793f-fa32-4659-8b1f-58cd9e646bec)
![Image](https://github.com/user-attachments/assets/97fb9246-1638-4fc4-85fa-aacfef8233cb)

 - Version 1.2.1

**Comment by realpaaao** [comment]
Swap tx : 0xf12ad9194575d7e04fe22e6bfcf6eec71f067e1785fa5d61b569ace21cca14b7

**Comment by johnnyluo** [comment]
We are not going to implement this route for now , as swaping ERC20 need to deal with router contract , currently we are using walletcore to do it , but  walletcore doesn't support Maya

**Comment by realpaaao** [comment]
ok then @flypaper0 could you prevent this route to be swappable?

**Comment by johnnyluo** [comment]
closing #1335

**Comment by realpaaao** [comment]
QA done.
