### ISSUE TITLE
[BUG] Inconsistent Request Payload Structure Between Android and iOS in /complete/:sessionID/keysign Endpoint

### ISSUE THREAD

**Issue by Ehsan-saradar** [vultisig/vultisig-ios#1340]
**Describe the bug**
The request payload sent to the /complete/:sessionID/keysign endpoint (referenced in [handler.go, line 58](https://github.com/vultisig/vultisig-relay/blob/main/server/handler.go#L58)) differs between Android and iOS platforms.

Example for IOS:
```

{
  "s": "416ceccaf7759dbe63aadd20ebb023720615969ebb724d0b0b446fb74b68ec66",
  "derSignature": "3045022100e21b119988071e1c79095d203e1323067ab3be5f72ae8139176566c761ee93200220416ceccaf7759dbe63aadd20ebb023720615969ebb724d0b0b446fb74b68ec66",
  "recoveryID": "01",
  "msg": "iimaWsFPDixPuGxt23Y/MTMU+K7MaquMI/+aTEt/y7E=",
  "r": "e21b119988071e1c79095d203e1323067ab3be5f72ae8139176566c761ee9320"
}
```

Example for Android:

```
{
  "Msg": "InW+SpqcN1RABxvAwrL9nMLj6UlIwpWmzwbu2DM6SHE=",
  "R": "d00a142d11fa446d900f85a6e22f1e59ba274619521310c6d9b02fdec8427138",
  "S": "1d9ad0c28756b2691d0135aa69e92c367366e13b87bda78ece320b62fcf9dce3",
  "DerSignature": "3045022100d00a142d11fa446d900f85a6e22f1e59ba274619521310c6d9b02fdec842713802201d9ad0c28756b2691d0135aa69e92c367366e13b87bda78ece320b62fcf9dce3",
  "RecoveryID": "01"
}


```
The structure inconsistency is causing issues with iOS/macOS devices, while Android works correctly and can fetch the transaction hash in VultiConnect. It would be beneficial to standardize the request payload format across platforms to ensure compatibility.

**Comment by johnnyluo** [comment]
@Ehsan-saradar  , the payload is the same , but just the field Name is different , IOS does't start the first character uppercase 
can you decode the json , ignore the field name's case?

**Comment by johnnyluo** [comment]
Closing , vulticonnect will implement a custom json deseriaze , ignore field name's case
