### ISSUE TITLE
[ADD] Replace blowfish (Deadline November 3rd, 2024)

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-ios#1345]
ScamSniffer has the best dApp detection. For simulations, you can choose between Alchemy, Blockaid, and Tenderly.

I've tested **ScamSniffer**, and until now, it is the best alternative. 

**The documentation:**
https://docs.scamsniffer.io/reference/postv1checkrequest

`curl --request POST \
     --url https://check-api.scamsniffer.io/v1/checkRequest \
     --header 'accept: */*' \
     --header 'content-type: application/json' \
     --header 'x-api-key: demo-api-key' \
     --data '
{
  "chainId": "0x1",
  "origin": "blur-trade.com",
  "detail": {
    "method": "eth_sendRawTransaction",
    "params": [
      "0xAFD2C82D0768A13d125ca5DA0695263840E68807"
    ]
  }
}
'`

**Blockaid**
They have the same features. Therefore, we can't test it without contacting and scheduling a call with them, which is similar to what we've done with **Blowfish**.

- [x] I've contacted them already

**Comment by johnnyluo** [comment]
since this one has been removed , so let's close this issue
