### ISSUE TITLE
[UPDATE] Reshare - OnboardingPairing view

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1357]
After feedback from JP we updated all pairing views to be cleaner and less packed.
Please verify that pairing views match on all flows:

 [Reshare](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=12051-8148&t=ZWEZLv7NHipL8q9g-4)

**Comment by realpaaao** [comment]
QA done.
