### ISSUE TITLE
[UPDATE] Send - Pairing view

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1358]
After feedback from JP we updated all pairing views to be cleaner and less packed.
Please verify that pairing views match on all flows:

 [Send](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=15130-30956&t=ZWEZLv7NHipL8q9g-4)

**Comment by realpaaao** [comment]
QA done.
