### ISSUE TITLE
[BUG] Broken deeplink flow

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1368]
**Describe the bug**
Scanning the QR code via native app only opens the app not the send view.

**Video**
https://github.com/user-attachments/assets/3abf8878-2553-4762-99ab-ade328ec3e4d

**Comment by Rockindash** [comment]
Tested the deeplink for all the possible flows listed below and it seems to work fine.
- Keygen
- Send
- Swap

**Comment by realpaaao** [comment]
QA done.
