### ISSUE TITLE
[BUG] Bad formatting when pasting numbers

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1370]
**Describe the bug**
when pasting numbers with kommas and decimal saperator, the kommas and separators get adjusted to `.` to have a unviable input.

**To Reproduce**
1. paste number with komma and point separators
2. See error

**Expected behavior**
Please include a logic that checks the currency and what separators are used for decimals and big numbers.
According to that always update the pasted numbers. Also include that logic when typing in numberst that the last separator is always the decimal separator for the selected currency

 - Version 1.3.00

**Comment by johnnyluo** [comment]
@Rockindash , has this been fixed?

**Comment by Rockindash** [comment]
Yes, it was fixed in the following PR:
https://github.com/vultisig/vultisig-ios/pull/1501
