### ISSUE TITLE
[ADD] [Customer Request] Silent Payments for BTC

### ISSUE THREAD

**Issue by SxMShaDoW** [vultisig/vultisig-ios#1374]
**Is your feature request related to a problem? Please describe.**
Silent payments allow a single address to resolve to a BTC address but maintain privacy. 

https://silentpayments.xyz/docs/explained/

In March of 2022 Ruben Somsen proposed “[Silent Payments](https://gist.github.com/RubenSomsen/c43b79517e7cb701ebf77eec6dbb46b8),” a new approach to reusable payment codes that removes the need for a notification transaction (the major drawback of [BIP 47 payment codes](https://silentpayments.xyz/docs/comparing-proposals/bip47)) by entirely leveraging information that was already in the transaction to signal to the recipient when funds are intended for them. Silent Payments makes use of advances in Bitcoin scanning to remove the need for a notification transaction, thereby improving scaling and privacy associated with reusable payment codes (with a key trade-off we’ll address later).

**Describe the solution you'd like**
Generate a silent payment address

**Describe alternatives you've considered**
Generate new vaults for BTC addresses 

**Additional context**
I know we are not trying to become a BTC app and support a lot of methods (lightning, taproot, etc) BUT it would be great to at least add silent payments for privacy purposes.

**Comment by SxMShaDoW** [comment]
@realpaaao - let me know if I should add feature requests in another repo.

**Comment by johnnyluo** [comment]
I don't think this will work , based on the explaination of silent payment ,it need to create a one time address 
`(3) a shared secret (generated using the Silent Payment public key and the user’s UTXO private key using [ECDH](https://en.wikipedia.org/wiki/Elliptic-curve_Diffie%E2%80%93Hellman)) that only Alice and Bob can know`

In vultisig's case , it never construct a private key, it doesn't exist
