### ISSUE TITLE
[ADD] [Customer Request] Noble (Cosmos) Chain

### ISSUE THREAD

**Issue by SxMShaDoW** [vultisig/vultisig-ios#1375]
**Is your feature request related to a problem? Please describe.**
Ability to use a Noble Address to receive issuance assets (USDC,EURe, etc). 

**Describe the solution you'd like**
Add Noble Chain to the list and receive assets on it.

**Describe alternatives you've considered**
Utilize other networks for USDC

**Additional context**
https://www.noble.xyz/

**Comment by johnnyluo** [comment]
are you talking about add `Noble` chain support to Vultisig?

**Comment by SxMShaDoW** [comment]
Correct - to be able to receive assets via the Noble chain: noble1wXXXXXXXXXXXXXXXXXXXXXX

**Comment by SxMShaDoW** [comment]
@johnnyluo / @realpaaao - is there a complexity on why we can't add noble addresses? Its the 6th most popular USDC network (and catching up to take the 5th spot soon) and higher than AVAX which is already supported.

https://usdc.cool/

![CleanShot 2024-11-12 at 11 42 45](https://github.com/user-attachments/assets/309db309-4be8-4fe4-99b5-257eeafc6fb1)

**Comment by johnnyluo** [comment]
we should be able to support it , since it is already added to wallet-core , but not sure why TrustWallet doesn't even have it

**Comment by SxMShaDoW** [comment]
@jpthor mentioned that it will be used on TC App Layer. Would love for some support in the wallet before then - especially if it doesn't require extra PR to an external repo.

**Comment by johnnyluo** [comment]
will look into it, cc: @enriquesouza

**Comment by enriquesouza** [comment]
It seems wallet core has it @johnnyluo I can add support to it if nothing goes wrong.

**Comment by enriquesouza** [comment]
Added https://github.com/vultisig/vultisig-ios/pull/1600

**Comment by SxMShaDoW** [comment]
@enriquesouza - AMAZING! Note: There are technically other coins on noble outside of USDC (I believe there are 5 or so) BUT I don't use them - so this is amazing!

**Comment by realpaaao** [comment]
QA done.
