### ISSUE TITLE
[BUG] No FastSign on 3-4 setup with Vultiserver included

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1377]
**Describe the bug**
After creating/resharing an active vault 3-4 setup and trying to sign a transaction with `FastSign` it is not possible to discover the server and sign a transaction. Neither opens the pairing QR code view.

**To Reproduce**
1. Create 3-4 active vault
2. try to use fast sign 
3. See error

**Expected behavior**
Please implement a logic that if a 3-4 active vault setup is detected it opens the Qr pairing view with vultiserver joining and the possibility to join with the 3rd device to be able to meet the threshold.

**Screenshots**
![Image](https://github.com/user-attachments/assets/b21f5e58-6911-4e6b-91dd-042fabbd424a)

 - Version 1.4.1

**Comment by johnnyluo** [comment]
@flypaper0 Please double check when user trying to do fastsign , if the vault has more than three parties , please show QR code Pair view

**Comment by realpaaao** [comment]
QA done

**Comment by flypaper0** [comment]
> @flypaper0 please improve that the server and device joining is auto selected and signing kicks off automatically when threshold is reached



> @flypaper0 please improve that the server and device joining is auto selected and signing kicks off automatically when threshold is reached

better to make it in separate task
