### ISSUE TITLE
[BUG] Able to create a 3-4 active vault

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1378]
Please add logic that on active vault creation it is only possible to create a 2-3 vault and prohibit creating any bigger vaults with Vultiserver included.

**Comment by johnnyluo** [comment]
why is that?

**Comment by realpaaao** [comment]
@johnnyluo because when having a 3-4 active vault it is somehow impossible to fast sign see #1377 as it just is looking for the server without the 3rd deivce needed to reach threshold

**Comment by johnnyluo** [comment]
I am going to close this one , we will allow user to create an active vault with more than 3 parties ,  will fix the fast sign view to show QR code when there are more than 3 parties in the vault
