### ISSUE TITLE
[BUG] EVM chains do not autodiscover tokens

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1379]
**Describe the bug**
When refreshing to autodiscover tokens on EVM, nothing happens.

**Expected behavior**
Autodiscover tokens consistently

 - Version 1.4.1

**Comment by johnnyluo** [comment]
This could related to rate limiting on 1inch api endpoint

**Comment by realpaaao** [comment]
@johnnyluo only possible to improve when upgrading api? Or maybe other possibility?

**Comment by johnnyluo** [comment]
We will be switching to use THORWallet api

**Comment by realpaaao** [comment]
QA done.
