### ISSUE TITLE
[BUG] TC unbond memo broken

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1382]
**Describe the bug**
The Thorchain unbond memo is wrongly constructed, included the unbonding amount as payload. Making it impossible to correctly withdraw

**Expected behavior**

- [ ] Please adjust memo to include the amount itself, denominated in `1e8` format.
- [ ] No RUNE amount should be in the payload, please reduce payload rune to dust of `0.00000001` Rune

**Screenshots**
![Image](https://github.com/user-attachments/assets/63e039ef-cd07-4d10-b8b6-3d1f64192557)

 - Version 1.4.1

**Comment by johnnyluo** [comment]
1.The screenshot is confusing , because it is `bond` , not `unbond`
2. The memo for unbond is constructed correctly , however the verify screen can be improved
<img width="1409" alt="image" src="https://github.com/user-attachments/assets/23a25ad1-9b77-4e5d-9a8a-4507227d7e22">

**Comment by realpaaao** [comment]
Qa done.
