### ISSUE TITLE
[ADD] Jupiter support for SPL discovery

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1391]
To have a more complete SPL discovery we can use Jupiter API to discover more tokens:

https://station.jup.ag/docs/token-list/token-list-api

https://www.jupresear.ch/t/introducing-the-ecosystem-token-api-and-standard/20601

Please use andorid implementation as reference

**Comment by johnnyluo** [comment]
fixed in #1399

**Comment by realpaaao** [comment]
@enriquesouza fetching tokens produces an error on my end and not able to get Juptier list: 
![Image](https://github.com/user-attachments/assets/67ddf84b-267c-47da-935a-824da21daa14)

Also happens on testflight version when removing and adding SOL angain.

**Comment by realpaaao** [comment]
QA done.
