### ISSUE TITLE
[IMPROVE] Error message display

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1396]
We need to improve the display of errors when a error in a transaction occurs.

![Image](https://github.com/user-attachments/assets/660e9c2d-a510-4bde-a03d-eae0d2384bf6)

This is not a friendly way. 
Please use our Error view UI and just display the error "Insufficient funds, please try again"

**Comment by johnnyluo** [comment]
this error give us more information when we need to investigate anything for customer , so I would like to keep it
