### ISSUE TITLE
[BUG] When FastSign , it should always using Relay server

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-ios#1405]
**Describe the bug**
Currently , network mode "Internet" , "Local" , user can change it when doing keygen for "Secure" vault , or doing keysign with "Secure" vault , and once user change it , it saved locally , next time it will default to user's selection
For example , if I created a secure vault , and during the process , I choose to use "Local" network , then my preference has been saved, next time when we do keysign / keygen again , it will default to "Local" 

However , fastsign / fast vault / active vault , it can only work with relay server

Default to Relay server when working witih fast sign / fast vault / active vault

**Comment by realpaaao** [comment]
QA doine.
