### ISSUE TITLE
[ADD] Automatic activation of biometrics for fast sign

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1425]
To improve convenience, let us automatically enable bimetric signing for FastSign when creating a Fast or Actice Vault.

If the user does not wish that, he can disable it in the settings.
Please include logic if a user does not have biometrics on his phone.

**Comment by johnnyluo** [comment]
fixed in #1430

**Comment by realpaaao** [comment]
QA done.
