### ISSUE TITLE
[BUG] unable to scan TON address

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1426]
**Describe the bug**
Scanning TON address from TON telegram wallet to send TON will not resolve the QR correctly.

**Expected behavior**
Able to scan TON addresses

**Screenshots**
![Image](https://github.com/user-attachments/assets/9f141aae-44f6-4c6c-a242-3085732ac52c)

 - Version 1.5.0

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/1466
