### ISSUE TITLE
[BUG] Always showing Biometrics for fast sign

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1435]
**Describe the bug**
Biometrics for FastSign is currently always shown no matter the vault type, even if no Fast Sign is available.

**Expected behavior**
Please check when FastSign is available and only show biometrics options for those vaults

**Screenshots**
![Image](https://github.com/user-attachments/assets/09a0f4df-dce1-4018-8918-5bb66ab2dd00)

 - Version `main `branch

**Comment by johnnyluo** [comment]
duplicated with #1407 , closing
