### ISSUE TITLE
[BUG] Unable to swap small amount of tokens on ETH

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1456]
**Describe the bug**
Unable to swap "small" amounts of ETH as high number of tokens are required even if the slip or gas costs are not deducted from the asset

**Expected behavior**
Able to swap wanted token amounts.

**Screenshots**
![Image](https://github.com/user-attachments/assets/e36e51ed-9c6b-4c50-8b0f-bc38e3e0d88b)

 - Version 1.5

**Comment by johnnyluo** [comment]
I think the recommended amount is coming from THORChain quote
