### ISSUE TITLE
[BUG] Switch Token Discovery to use thorwallet api

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-ios#1479]
**Describe the bug**
Currently we are using 1inch to do token discovery , which get rate limit often
please switch to use https://api-v2-prod.thorwallet.org/api#/

**Comment by enriquesouza** [comment]
On my tests I found out we still need to add some chains (Base, Polygon, Optimism, Zk aren't supported by this API) to bring the balances and the tokens. 

https://docs.google.com/spreadsheets/d/1RXjdI4ql1YN3ZyfJjThvgL9OQc9uT2iveO2d_grVOTk/edit?usp=sharing
