### ISSUE TITLE
[BUG] Unable to send tx on EVM

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1481]
**Describe the bug**
When sending tokens on EVM chains many times the gas limit of `23,000` is not enough, leading to a failed tx. Especially on Arbitrum. 

**To Reproduce**
1. Go to EVM chain
2. Send tx with standard gas limit
3. See error

**Expected behavior**
Able to send txs on EVMs without problem

 - Version 1.6.0

**Additional context**
When increasing gas limit to `100,000` it seems to go through consistently.

**Comment by johnnyluo** [comment]
is it specifically for ARB? I think on ETH 23000 is enough to send ETH , and we use 100K for ERC20

**Comment by realpaaao** [comment]
So far I only could duplicate on ARB

**Comment by realpaaao** [comment]
QA done.
