### ISSUE TITLE
[BUG] Unable to send ARB.ETH

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1485]
**Describe the bug**
When sending ARB.ETH the transaction gets signed but never gets broadcasted or able to locate

**To Reproduce**
1. send ARB.ETH
2. See error

**Expected behavior**
Able to send ARB.ETH

**Screenshots**
![Image](https://github.com/user-attachments/assets/0a83a114-4967-4c8a-ad8b-b9e805b8c722)

 - Version 1.6

**Comment by enriquesouza** [comment]
We fixed the code in 120K for the estimated gas fee.

https://github.com/vultisig/vultisig-ios/blob/lifi-price-rate/VultisigApp/VultisigApp/Model/Coin.swift#L145

Test Arb:
https://arbiscan.io/tx/0x52cb5dcb19b3d4f7721ca8778f8d841bd48d37727aa842f694c5d95fd30aff84

Test Arb ETH:
https://arbiscan.io/tx/0xdbf90674808532fd7d36b0b765d54108e7a9b84101c6f621dd10693c45ad9d99

**Comment by enriquesouza** [comment]
<img width="951" alt="image" src="https://github.com/user-attachments/assets/a2640977-debb-4b06-8363-03b977603740">

The reason we are not being able to send is the gas limit. It uses a lot of it. 120 is not enough there was cases it use 160k
