### ISSUE TITLE
[BUG] last transaction shows again after selecting vault in folder

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1490]
**Describe the bug**
After doing a transaction and changing to a vault, which is located in a folder, triggers to show the old tx again and unable to open the vault.

**To Reproduce**
1. Do a tx
2. change to a vault which is located in a folder
3. See error

**Expected behavior**
Able to select vault without triggering old tx again

 - main branch

**Comment by Rockindash** [comment]
@realpaaao This PR should fix all the underlying vault selections within a folder bugs.
https://github.com/vultisig/vultisig-ios/pull/1497

If you get a chance, can you please verify??

**Comment by johnnyluo** [comment]
it had been fixed in #1497

**Comment by realpaaao** [comment]
QA done.
