### ISSUE TITLE
[ADD] Terra ecosystem

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1496]
Please integrate the Terra chains:

- [ ] Terra Classic (columbus-5)
- [ ] Terra (phoenix-1)

please support coin types for both chains:
- [ ] 330
- [ ] 118

Also please support CRW-20 tokens with teh "Choose Token" and "Custom Token" UX flow.

**Comment by johnnyluo** [comment]
Is Terra still alive?

**Comment by realpaaao** [comment]
@johnnyluo yes. We also need it to complete something [REDACTED]

**Comment by realpaaao** [comment]
@enriquesouza I can't send LUNC out of the wallet, always prompting:

![Image](https://github.com/user-attachments/assets/7838b00e-14c1-44c3-a541-5abbb508c230)


LUNA works fine

**Comment by realpaaao** [comment]
QA done.
