### ISSUE TITLE
[IMPROVE] SOL token search

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1500]
Most SOL SPL tokens can't be found on token search when choosing tokens.

Please improve/verify the search if it pulls correctly from jupiter to find more tokens.

**Comment by enriquesouza** [comment]
https://coinmarketcap.com/pt-br/view/solana-ecosystem/

Tests with unknown tokens (to myself):

1. 7ZqzGzTNg5tjK1CHTBdGFHyKjBtXdfvAobuGgdt4pump -> BARSIK :: OK
2. 3B5wuUrMEi5yATD7on46hKfej3pfmd7t1RKgrsN3pump - BILLY :: OK
3. 5mbK36SZ7J19An8jFochhQS4of8g6BwUjbeCSxBSoWdp - MICHI :: OK
4. FvgqHMfL9yn39V79huDPy3YUNDoYJpuLWng2JfmQpump - Urolithin A $URO :: OK
5. 8NNXWrWVctNw1UFeaBypffimTdcLCcD8XJzHvYsmgwpF - Brainlet :: OK
6. DPaQfq5sFnoqw2Sh9WMmmASFL9LNu6RdtDqwE1tab2tB - Skibidi Toilet :: OK
7. GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump - Act I : The AI Prophecy ACT :: OK
8. GtDZKAqvMZMnti46ZewMiXCa4oXF4bZxwQPoKzXPFxZn - nubcat NUB :: OK

**Comment by realpaaao** [comment]
@enriquesouza I am not referring to CA's but searching with ticker, can we improve that they are viewable with that?
Amin lately implemented that on android side

**Comment by enriquesouza** [comment]
I've done it @realpaaao on this PR https://github.com/vultisig/vultisig-ios/pull/1589

**Comment by realpaaao** [comment]
Qa done
