### ISSUE TITLE
[BUG] error when sending DOT

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1504]
**Describe the bug**
When sending DOT, the initating device always gets the error "transaction already imported" while the tx is signed and broadcasted succefully and tx has is shown correctly on pairing device.

**To Reproduce**
1. Send DOT
2. wait for verification
3. see error on initating device

**Expected behavior**
Show tx hash consistently

**Screenshots**
![Image](https://github.com/user-attachments/assets/7b3ab996-b007-401b-8af1-aec275e50b37)

 - Version 1.6.0

**Comment by enriquesouza** [comment]
<img width="456" alt="image" src="https://github.com/user-attachments/assets/0fda592f-538e-4c34-a90b-a44cd0f581e0">

**Comment by enriquesouza** [comment]
I am not being able to simulate that

Device one

<img width="461" alt="image" src="https://github.com/user-attachments/assets/48cfb12e-9ddc-4e2b-bbb7-679bd8f05514">


Device two

![image](https://github.com/user-attachments/assets/034fff35-8647-40c5-a47e-5e25c2623f38)

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/1608
