### ISSUE TITLE
[BUG] Inline Navigation title enlarged

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1507]
**Describe the bug**
Inline Navigation title enlarged

**To Reproduce**
1. Select a chain.
2. Tap on "Choose chain".

**Expected behavior**
Set navigation titles to be inline.

**Screenshots**
![image](https://github.com/user-attachments/assets/a19c6423-697d-4697-b5ac-fba196a64913)

**Comment by realpaaao** [comment]
QA done.
