### ISSUE TITLE
[ADD] Support method signing without broadcasting

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1520]
To be able to fully use Vulticonnect with other interfaces/dApps we need the possibility to support signing without broadcasting in the apps. 
Needed: 
`eth_signTypeData_v4` and `self sign`

**Comment by Ehsan-saradar** [comment]
@realpaaao @johnnyluo 

We need to support  off-chain message signing or a personal message signing. In DeFi and other dApps, signing a custom message off-chain is used to prove wallet ownership without actually making an on-chain transaction.
To support off-chain (personal) message signing, we need to update both Vultisig and Vulticonnect. This new flow will allow Vultisig to sign messages without broadcasting them directly. Instead, Vultisig will store the signed message via the Vultisig Relayer, and Vulticonnect will pick up the signed message from the Relayer for broadcasting to the network as needed.

Also we need to update vultisig to support custom message signing too.

**Comment by realpaaao** [comment]
Closing as completedin https://github.com/vultisig/commondata/pull/20
