### ISSUE TITLE
[BUG] Balances not updating with pulldown

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1525]
**Describe the bug**
When refreshing on `pulldown` balances are not updating and app needs to be restarted.
Also when refreshing, changing vault and refreshing again, pulls balances from vault selected before or crashes the app occasionally(just happened one time on iPad).

**To Reproduce**
1. Go to vault
2. refresh on `pulldown`
3. See error
4. change vault
5. refresh on `pulldown`
6. See error

**Expected behavior**
Balances refresh consistantly and no balances of other vaults are shown.

**Screenshots**
https://github.com/user-attachments/assets/a27e59a1-a5a6-49d8-8f3a-297785e2664c

System:

 - Version 1.6.0

**Comment by johnnyluo** [comment]
fixed in #1553

**Comment by realpaaao** [comment]
QA done. Can't reproduce anymore on main
