### ISSUE TITLE
[ADD] UI for vultiserver backup verification

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1528]
Please add a view that the user can put in a code to verify the receipt of the backup of his vultiserver backup share.
Please only trigger this view on vault creation where a vultiserver is included (fast or active vault).
Check against code saved on server.
When going back, it starts at vault setup selection

![Image](https://github.com/user-attachments/assets/ed979941-4a0f-4daf-9425-215778f267e9)

**Comment by johnnyluo** [comment]
FYI:  Add generate verification code , and also endpoint to verify code 
https://github.com/vultisig/VultiServer?tab=readme-ov-file#resend-vault-share-and-verification-code

**Comment by realpaaao** [comment]
Qa done.
