### ISSUE TITLE
[BUG] Updating Backup export option

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1539]
**Describe the bug**
Checking the option to add a completion handler for ShareSheet dismiss.

**Comment**
I just saw a user go to backup and then they “X”’d the backup screen and then the backup screen disappeared. 
They thought they had back-ed up but did not. 

**Screen recording**
https://github.com/user-attachments/assets/93896932-8892-46d5-80c9-06ecca568d14

**Comment by realpaaao** [comment]
It still happens when opening and closing without saving, the banner vanishes. @Rockindash
