### ISSUE TITLE
[BUG] deleting old backups crashes the app

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1548]
**Describe the bug**
When importing old backups and deleting them, crashes the app

**To Reproduce**
1. import old backup
2. delete it
3. See error

**Expected behavior**
Delete without crash

System:
 - Version 1.7.0

**Comment by johnnyluo** [comment]
This should have been fixed in https://github.com/vultisig/vultisig-ios/pull/1540

**Comment by realpaaao** [comment]
QA done.
