### ISSUE TITLE
[BUG] Wrong memo on Maya bonding

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1566]
**Describe the bug**
Bonding for MAYA has the same memo as bonding on TC, which is not correct.
Especially sending CACAO as tx payload

**Expected behavior**
Correct bonding according to https://docs.mayaprotocol.com/node-docs/bonding-and-unbonding-guide

**Screenshots**
![Image](https://github.com/user-attachments/assets/ba8d445c-b88c-474e-a4ab-8f5c424e3c0d)

System:
 - Version 1.7.1

**Comment by enriquesouza** [comment]
This is the PR:
https://github.com/vultisig/vultisig-ios/pull/1579

**Comment by realpaaao** [comment]
@enriquesouza Do you think we can rename the labels and improve some fields?
As atm having bond two times is confusing.

Could we do:

- [ ] Remove `Amount` in `Bond` tab, remove `(optional)` from Provider label
- [ ] Remove `Amount` in `Unbond` tab, remove `(optional)` from Provider label
- [ ] Change `Bond` and `Unbond` to `Add Bondprovider to WL` and `Remove Bondprovider from WL`
- [ ] Change `Bond Maya` and `Unbond Maya` to just `Bond` and `Unbond` , as no Maya is bonded.

**Comment by enriquesouza** [comment]
- [ x ]  remove (optional) from Provider label -> They are optional on Thor. It will be a big change.

**Comment by realpaaao** [comment]
QA done.
