### ISSUE TITLE
[BUG] Dynamic gas limit not working on BNB

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1573]
**Describe the bug**
Dynamic `gas limit` fetching for BNB is not working correctly. Users are still running into the problem sending BNB without increasing limit automatically

**To Reproduce**
1. Send BNB
2. See error

**Expected behavior**
Able to send BNB withou adjusting `gas limit `

**Screenshots**
![Image](https://github.com/user-attachments/assets/7517a992-a0fd-463c-a3ab-e7c7db4f057b)
![Image](https://github.com/user-attachments/assets/6f932f38-8297-43db-b0c8-329e9a084c84)

System:
 - Version 1.7.1

**Comment by Noahlucas2** [comment]
> **Describe the bug** Dynamic `gas limit` fetching for BNB is not working correctly. Users are still running into the problem sending BNB without increasing limit automatically
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Send BNB
> 2. See error
> 
> **Expected behavior** Able to send BNB withou adjusting `gas limit `
> 
> **Screenshots** ![Image](https://private-user-images.githubusercontent.com/167348323/388361510-7517a992-a0fd-463c-a3ab-e7c7db4f057b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjkzNTgsIm5iZiI6MTczMjE2OTA1OCwicGF0aCI6Ii8xNjczNDgzMjMvMzg4MzYxNTEwLTc1MTdhOTkyLWEwZmQtNDYzYy1hM2FiLWU3YzdkYjRmMDU3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNjA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDlmYzViNWRjZmYxZWM2MjZiODYyYTIzM2MxMDZlMTA3MjZjM2ZkZjMyZDBkZGExNjJmMjIzYmFhNWYwZDFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zeIdlw9J_D3W8zri1S-VE1_M3_Z9N9ubTNThdfNkwkY) ![Image](https://private-user-images.githubusercontent.com/167348323/388361544-6f932f38-8297-43db-b0c8-329e9a084c84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjkzNTgsIm5iZiI6MTczMjE2OTA1OCwicGF0aCI6Ii8xNjczNDgzMjMvMzg4MzYxNTQ0LTZmOTMyZjM4LTgyOTctNDNkYi1iMGM4LTMyOWU5YTA4NGM4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNjA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDE3OGI3MWFmNTY0OTM3NTBhMzZhYzljMDA3MDA0Zjg3NDMyNjg4NWU3MjMxZTE1Y2IxZTVlOGJmMDdmZTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fgE0c5cOr2llioCZr1KQftWxehFEafwpCa2PkEeyqWc)
> 
> System:
> 
> * Version 1.7.1



Hello @flypaper0 If the automatic fetching isn’t working, you might need to manually increase the gas limit when sending BNB. Look for the option to set the gas limit in the transaction settings.

**Comment by realpaaao** [comment]
QA done.
