### ISSUE TITLE
[BUG] Scanning OSMO address QR does not select OSMO chain

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1578]
**Describe the bug**
Scanning OSMO address QR does not select OSMO chain

**To Reproduce**
1. Scan OSMO address QR
2. See error

**Expected behavior**
Select OSMO chain automatically

System:

 - Version 1.7.1

**Comment by johnnyluo** [comment]
@Rockindash, does this one fixed with your latest changes in https://github.com/vultisig/vultisig-ios/pull/1647

**Comment by johnnyluo** [comment]
Closing, as long as user have OSMO chain enabled , then the chain will be selected
