### ISSUE TITLE
[IMPROVE] RUNEPool removal

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1592]
Please change `basis points` to `percentage `on removal, it is easier for the user.
Please remove affiliate fee and hardcode it to `vi` with 50 bps .

![Image](https://github.com/user-attachments/assets/ab79ea43-a4cc-43d4-8040-0da932d5f7b8)

**Comment by enriquesouza** [comment]
@realpaaao what do you mean?

Please change basis points to percentage on removal, it is easier for the user. -> Rename the label from Basis Point to Percentage?
Please remove affiliate fee and hardcode it to vi with 50 bps . -> Replace 50 to vi?

**Comment by realpaaao** [comment]
@enriquesouza 
1) yes change `Basis point` to `Percentage` label and let user withdraw percentages 
2) Just remove the optinal label that the user can adjust it.

**Comment by enriquesouza** [comment]
this PR https://github.com/vultisig/vultisig-ios/pull/1628 solves https://github.com/vultisig/vultisig-ios/issues/1592

**Comment by realpaaao** [comment]
QA done.
