### ISSUE TITLE
[BUG] Wrong swap formatting

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1595]
**Describe the bug**
The layout and formatting of the swap page does not mirror figma, please change that it mirrors figma:
Currently:
![Image](https://github.com/user-attachments/assets/0dbb7ea7-6f2b-44a9-acb9-d33ee202b500)

[Figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=5633-5551&t=qyzgTpQO8jkm2AiJ-4):
![Image](https://github.com/user-attachments/assets/42ded5eb-4c1c-44f2-bec3-df0d4193dfb1)

System:

 - Version 1.8.0

**Comment by Rockindash** [comment]
This was fixed in the following PR:
https://github.com/vultisig/vultisig-ios/pull/1664

Will be closing this as of now.

**Comment by realpaaao** [comment]
QA done.
