### ISSUE TITLE
[BUG] Able to proceed Bonding on MAYA without selected asset

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1618]
**Describe the bug**
Able to proceed to bond on MAYA without selecting any assets

**Expected behavior**
Include check that an asset needs to be selected.

**Screenshots**
![Image](https://github.com/user-attachments/assets/b289aa67-8808-45d5-8668-461578d3f4a7)

System:
 - Version 1.8.1

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/1626/files

**Comment by realpaaao** [comment]
QA done.
