### ISSUE TITLE
[BUG] WEWE without price

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1623]
**Describe the bug**
$WEWE does not show prices

**Expected behavior**
Show price of $WEWE

**Screenshots**
![Image](https://github.com/user-attachments/assets/d43f561f-18f6-4a7c-95cf-0e8145b8760f)

System:
 - Version 1.8.1

**Comment by johnnyluo** [comment]
![Image](https://github.com/user-attachments/assets/0d936a3d-f680-48bb-b4ee-d9df92072bae)
works fine on my MacOS app

**Comment by realpaaao** [comment]
Was temporary error, closing
