### ISSUE TITLE
[Update] Add network fee to KeysignPayload

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#1641]
**Describe the bug**
Could not setup network fee cells for the pair device since the gas and gasInFiat value is missing from the KeySignPayload.

**Expected behavior**
Gas and GasInFiat can be a part of KeySignPayload. It makes it easier to add network fee cell to keysign verify and done view.

**Comment by johnnyluo** [comment]
network fee should be calculated based on the keysign payload
