### ISSUE TITLE
[BUG] Wrong copy text for complete view on pairing device

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1672]
**Describe the bug**
When completing a send the pairing device shows a dead swap progress link in the tx hash section

**Expected behavior**
Remove and be congruent with figma

**Screenshots**
![Image](https://github.com/user-attachments/assets/772f1621-524f-47fe-a7b9-9b0cb33e3787)

System:
 - Version 1.9.1

**Comment by johnnyluo** [comment]
Also , can we make sure to remove "Join Keysign" as title , and show " Transaction Complete" instead

**Comment by realpaaao** [comment]
QA done.
