### ISSUE TITLE
[FEATURE] Chain Priority

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#256]
- [x] All THORChain Chains
- [x] Solana
- [x] Maya Protocol and all Maya Supported Chains (Maya, Dash, Kujira)
- [x] Maya
- [x] Dash
- [x] Kujira
- [x] Arbitrum
- [x] Base
- [x] Polygon
- [x] Optimism
- [ ] Tron
- [x] Sui 
- [x] Cronos
- [x] Blast

Not supported by WC:
> - [ ] ~~PulseChain~~ (Not fully supported)
> - [ ] ~~TON~~ https://github.com/trustwallet/wallet-core/tree/master/src/TheOpenNetwork (Not fully supported)

Could not test because BRC-20 and BTC gas fees:
> - [ ] ~~Merlin~~ (Fees are too high to test at the moment, 90 USD per tx and exchanges suspended the network)

**Comment by enriquesouza** [comment]
As I checked here the Ton does not implement the preImage on Wallet Core. 

Solana implements it:
https://github.com/trustwallet/wallet-core/blob/f3b1224f061972ccd8a9104d04e26c2c4764b58b/src/Solana/Signer.cpp#L262

The Open Network does not:
https://github.com/trustwallet/wallet-core/blob/f3b1224f061972ccd8a9104d04e26c2c4764b58b/src/TheOpenNetwork/Signer.cpp

I've opened an issue to wallet core
https://github.com/trustwallet/wallet-core/issues/3797

**Comment by enriquesouza** [comment]
Trust wallet replied: https://github.com/trustwallet/wallet-core/issues/3797

Hi @enriquesouza, thank you for opening the issue.
We do not support TransactionCompiler functions for TON chain yet.
Please feel free to open a PR with the preimage and compile functions.

I'll keep this issue open to keep an eye on the issue.

**Comment by enriquesouza** [comment]
Sui:
https://github.com/trustwallet/wallet-core/issues/3816

**Comment by johnnyluo** [comment]
Close this one , it is not useful anymore , add individual issues when we need to add new chains
