### ISSUE TITLE
[UI]: Various Fixes

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#337]
# Creating New Vault Goes to Last Vault

When creating a new vault, it goes back to the previous vault, and doesn't open up new vault (make it priority)

- [x]  Done

# Creating New Vault, Latest Vault created out of Order

When creating a new vault, the New Vault is added in the second position and doesn't put newest vault on bottom of vault list. 
Need more than 3 vaults created. 

- [x] #372

# When viewing vault details, doesn't go back correctly
Have 3 vaults, select first vault, view vault details, go back
Loads wrong vault!

- [x] #365

# Going Back on KeySign drops All TX

When up to keysign part, going back drops the full tx, keep the tx, should just go back one layer

- [x]  done

# Wrong Vault on KeySign, doesn't go to Vault Selection Page

Have wrong vault on pair device, Scan QR code, button appears "choose vaults"
Does not got to Vault Selector page (it should)

- [x]  done

# Keysign does not check is not same device

Have a 20f2 vault, export 2nd vault share to 3rd device. 
Now 2nd and 3rd device have SAME vault share
Create a tx using 2nd device, and pair using 3rd device. Does not detect is SAME device share! Spins forever.
It should say "Error: Same Vault Share, Use Different Device"

- [ ]  done

Have wrong vault on pair device, Scan QR code, button appears "choose vaults"
Does not got to Vault Selector page (it should)

- [x]  done

# Menu Should Pan From Left

When tapping Menu (on the left), it pans from Right (wrong direction)

- [x]  done

# FaceID invoked when locking device

When app open, and the phone locks, 1second later whilst locked the FaceID Action is randomly invoked

- [x] done

# Prompt User for Vault Name on "Create New Vault"

User prompt for "Name your Vault". Populate this name thru the Create Vault QR code so all devices are synced. 

placeholder/default: `Main Vault`

- [ ] done

# Device Name on Vault Details

- [x] #368

<img width="422" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/b1dd4958-c89f-4c01-a7c0-e06055fca488">

# ID (This Device) on Vault Details

- [x] #369

<img width="475" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/492677b2-a382-41b8-9e12-27b85e6f4bb1">

# All Device Name is 3-digit only

Device names should only be 3-digit (not a long digit), easier to recognise

- [x]  done

# Auto-select Pair Device when Key-Sign

since only 1 device needed to be selected, make it auto

- [x] #366

<img width="488" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/d1aec21a-7969-48f7-83a2-6a82f3947a9d">

# Paste Button on Address field

paste in the clipboard

- [x] done

<img width="433" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/59afe8d6-013f-497d-b829-52f43ca2eade">

# Action Buttons have Outline

- [x] done

<img width="553" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/8007589d-caef-4e08-ace8-0e6b702f652e">

# Gear Icon for Vault Details

- [x] done

<img width="409" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/b6b01513-a9ce-4c87-91de-f0d11e439d85">

# Re-order Chains Function

Put the edit button bottom right and make it able to "re-order" the row of chains. 
Also do this for "Choose Tokens" - user can re-order the list of tokens

- [x] done

<img width="481" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/deb36f02-6105-4fda-8991-9a5994c3f0ab">

**Comment by johnnyluo** [comment]
> All Device Name is 3-digit only
Device names should only be 3-digit (not a long digit), easier to recognise

This one is already implemented , it will take effect when you create a new vault  , so I will mark this one as done

**Comment by enriquesouza** [comment]
@jpthor I cannot reproduce the behavior of going to vault details and coming back. It always loads correctly for me. I created 3 vaults to try to reproduce the error. I converted the task to an issue as well:

https://github.com/voltix-vault/voltix-ios/issues/365
