### ISSUE TITLE
[UI] Change notification when swap fails due to low gas

### ISSUE THREAD

**Issue by Hattrick1982** [vultisig/vultisig-ios#341]
![IMG_2680](https://github.com/voltix-vault/voltix-ios/assets/43502657/23f16d33-dd05-4333-9030-b26f4045e1f1)

This message could be improved to something like: "Insufficient balance (gas) to complete the  transaction. Please ensure you have enough gas to cover the transaction fees."

Ideally we also change the style sheet to be more in line with overall look and feel of the app.

**Comment by realpaaao** [comment]
Closing due to logic change, as errors get directly displayed in app before initiating the swap without the pop up error.
