### ISSUE TITLE
Hard to capture QR Code

### ISSUE THREAD

**Issue by SamYap0** [vultisig/vultisig-ios#352]
**Describe the bug**
I have two iPhones: a 14, and a 11 Pro.
Both on Voltix build 23.
It’s extremely difficult to get the 14 to scan QR generated on the 11 Pro (be it to create vault; or to sign Tx). Often no response even >10 or 20 seconds.
Using the 11 Pro to scan QR on the 14 is easy, just a few seconds to detect and proceed.

 - OS:  iOS 17.4.1 (both phones)
 - Voltix Version: 23

**Comment by johnnyluo** [comment]
Probably the QR code is a bit small. @Rockindash

**Comment by oxyc** [comment]
@Rockindash @johnnyluo not really optimal yet, this is scanning with an iphone 11 pro using latest build.


https://github.com/vultisig/vultisig-ios/assets/302736/0e3b67e9-44a6-4d46-a151-dec8d7a64d34

**Comment by johnnyluo** [comment]
@Rockindash , Could you please look into this?

**Comment by Rockindash** [comment]
Sure, I'll test it out again.

**Comment by oxyc** [comment]
Noteworthy is that the ios camera app picks it up easily

**Comment by johnnyluo** [comment]
it should get better , as part of https://github.com/vultisig/vultisig-ios/pull/451 , we zip the keysignmessage payload.
Before this zip , for a swap from btc -> RUNE , the payload size is 2129 bytes , after zip it is 976 bytes , and then covert to base64 it is 1300 bytes , so smaller , hopefully less data point will make it easier to capture. 

Based on my test , QR code generate from my iPad pro 11 inch , it is very easy to scan 
Qr Code generated from my iphone 11 , it is slightly harder to scan , but still get it done within a few seconds 

Will keep this open , and keep tracking QR code scan issues, if it still

**Comment by Rockindash** [comment]
One of the possible solutions. Shrink the URL itself using the Bitly library.
https://dev.bitly.com/docs/sdks/ios-sdk/

**Comment by oxyc** [comment]
I’ll test it in the next release and comment if it gets better or not with my devices. Currently scanning iphone 15 with an iphone 11 takes 20-60s for me so i don’t really try it anymore. scanning with ipad is fine.

**Comment by oxyc** [comment]
The above case that used to be 20-60s is now consistently a few seconds max. Reduced payload fixed it for me

**Comment by Rockindash** [comment]
Closing this issue for now, if the scan time significantly increases. Feel free to open it again.
