### ISSUE TITLE
BUG: Bad Vault from 1 device not DONE

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#354]
**Describe the bug**
- Build 23, iPad and iPhone
- Cellular
- Create vault, iPhone finished; iPad forever stuck on "generating EDDSA"
- Bad vault

**Expected behavior**
- Do not go past DONE until all devices finish, else user will have a bad vault

**Comment by johnnyluo** [comment]
This should have been fixed in PR: https://github.com/vultisig/vultisig-ios/pull/361
