### ISSUE TITLE
When viewing vault details, doesn't go back correctly

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-ios#365]
Have 3 vaults, select first vault, view vault details, go back
Loads wrong vault!

**Comment by enriquesouza** [comment]
https://drive.google.com/file/d/1zrVGcElS_p2PFqKahnxRM1x6Y3Olqqoe/view?usp=share_link

**Comment by enriquesouza** [comment]
@johnnyluo @flypaper0 @Rockindash I can't reproduce this error, can you?

**Comment by Rockindash** [comment]
I tried it as well but could not replicate it. It seems like this used to be an issue with previous build and has been resolved with the new ones.
