### ISSUE TITLE
BUG: Cannot have 1 chain

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#381]
1) create vault, it has default 4 chains set
2) turn off 3; expecting 1 left
3) Error

<img width="624" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/74aabd1b-e8ed-447b-b274-1658ed6b564e">

**Comment by enriquesouza** [comment]
Fixed

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/393
