### ISSUE TITLE
BUG: Mac on iPad does not launch camera. 

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#386]
1) Be on MacOs
2) Try to start camera
3) fails

Should invoke the front-facing camera option if detect Mac

**Comment by enriquesouza** [comment]
Apple has a bug and It is impossible to make it work for now. 

https://forums.developer.apple.com/forums/thread/748448
https://forums.developer.apple.com/forums/thread/743011

Branch:
https://github.com/vultisig/vultisig-ios/tree/Camera
