### ISSUE TITLE
Unable generate new vault

### ISSUE THREAD

**Issue by Saltycashew** [vultisig/vultisig-ios#398]
Using 1x iphone and 1 x ipad, unable to generate new vault. When using either to ‘start’ then using the other to scan the QR code it just gets to the attached error. Left for 5mins and no change or resolution. Switched to generate from the other device and the same error occurred. Image attached is the screen that it never gets past.

Both have been update to the latest version on testflight. 
![IMG_4496](https://github.com/vultisig/vultisig-ios/assets/167264250/065d9e23-9946-46b3-9549-5ca90ef412ee)

**Comment by johnnyluo** [comment]
This could because your local network doesn't support mDNS , could you try to choose `Cellular` option?  @Saltycashew

**Comment by johnnyluo** [comment]
I am closing this one for now , since there no new information , and highly likely it is related to mDNS
