### ISSUE TITLE
Reordering Chains is not permanent 

### ISSUE THREAD

**Issue by SamYap0** [vultisig/vultisig-ios#400]
**Describe the bug**
After reordering chains (e.g move THORChain to the top, on top of BTC), once we move to another screen and back, it reverts to default ordering.

**Expected behavior**
Ordered chains to remain.

**Smartphone (please complete the following information):**
 - Device: Both iPhone 11 Pro & 14
 - OS: 17.4.1
 - Version 24

**Comment by realpaaao** [comment]
@Rockindash would it be possible to also implement this request [https://github.com/vultisig/vultisig-ios/issues/449](url) ?
As than we could remove the re-arrange button on the right on main to be concruent with figma design.

**Comment by johnnyluo** [comment]
Instead of allow user to manually order the tokens, let's do this
1. Order by token balance , descending
