### ISSUE TITLE
Total balance double counts assets

### ISSUE THREAD

**Issue by oxyc** [vultisig/vultisig-ios#401]
**Describe the bug**

total balance sometimes double counts assets.

**To Reproduce**
1. Go to VaultDetailView (with at least 2 assets)
2. Wait for 1 asset balance to load
3. Enter ChainDetailView before secondary asset balances have finished loading 
4. Return to VaultDetailView
5. Note that the previously pending asset balance gets doubled counted

**Expected behavior**

Total balance to be correct.

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17.4.1

**Comment by oxyc** [comment]
if this went into build 25, it’s still not fixed.

**Comment by enriquesouza** [comment]
I believe we fixed that.
