### ISSUE TITLE
UI: Change all Voltix Texts to Vultisig

### ISSUE THREAD

**Issue by mikepocket** [vultisig/vultisig-ios#402]
<img width="1016" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/23121083/a9cf9072-6426-4d1a-b09c-1d5fbd8de15b">

Here it still says "Voltix App"

**Comment by mikepocket** [comment]
and also here:

<img width="209" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/23121083/743d9b2f-2a9b-4c4e-9b20-2cc56b5b51cc">

**Comment by mikepocket** [comment]
Also the link to X is still to the old account

**Comment by johnnyluo** [comment]
Wait for the next version, it should all changed then , build 24 was uploaded before we change it
