### ISSUE TITLE
wrong decimals for cacao fees when sending native cacao

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#403]
**BUG**
When sending CACAO on Maya Protocol, gas fees are displayed as 0.0002 CACAO but are correct on-chain with 0.2 CACAO

**To Reproduce**
1. Go to Mayachain asset in main vault 
2. Click on 'send'
3. Select 'Cacao' 
4. Scroll down to 'gas'
5. See gas fees 0.0002

**Expected behavior**
CACAO gas fees should be displayed as 0.2 CACAO

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/3e6d58d7-fc41-45e1-835b-61d648c00c4b)

**Smartphone (please complete the following information):**
 - Device: IPhone 11
 - OS: iOS 17.4.1
 - Version 1.0

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/407
