### ISSUE TITLE
wrong decimals for cacao fees when sending MAYA on MAYA Chain

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#404]
**BUG**
When sending MAYA on Maya Protocol, gas fees are set to 200 CACAO, therefore fails as amount + fees exceeds available balance.

**To Reproduce**
1. Go to Mayachain asset in main vault
2. Click on 'send'
3. Select 'MAYA'
4. Scroll down to 'gas'
5. See gas fees 200

**Expected behavior**
CACAO gas fees should be 0.2 CACAO

**Screenshots**
<img width="414" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/167348323/acdb3396-6099-4594-963c-ef3ba5d9f649">
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/acdca770-ed1a-4306-be0e-ee14e02f4697)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 17.4.1
 - Version 1.0

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/407
