### ISSUE TITLE
THORChain swap quote doesn’t include affiliate fee

### ISSUE THREAD

**Issue by oxyc** [vultisig/vultisig-ios#411]
**Describe the bug**

Currently THORChain swap estimates are misleading since they don’t include the 70bps affiliate fee.

https://github.com/vultisig/vultisig-ios/blob/68a7d629286ffcfb9d7aa7d54ab3354a0c4f024d/VultisigApp/VultisigApp/Utils/Endpoint.swift#L34

is missing the `affiliate_bps` parameter.

**Comment by johnnyluo** [comment]
fixed in. https://github.com/vultisig/vultisig-ios/pull/466

**Comment by oxyc** [comment]
This broke swaps to rune
