### ISSUE TITLE
[Coin] Refresh button doesn't work on coin page

### ISSUE THREAD

**Issue by flypaper0** [vultisig/vultisig-ios#413]
**Describe the bug**
- Go to Ethereum coin page
- Send ETH on wallet address from another device
- Await on Ethereum coin page and spam Refresh button 

Result: 
- Balance only refresh after closing Coin page and open again

**Comment by Rockindash** [comment]
@flypaper0 can you try the flow again?? Just tested it and it seems to work fine for me.
