### ISSUE TITLE
[Swap] Checks for TC swaps

### ISSUE THREAD

**Issue by flypaper0** [vultisig/vultisig-ios#422]
- Do not attempt to swap from an account abstraction or other smart contract wallet. Currently, any smart contract that interacts with THORChain needs to be whitelisted, so any swaps from a smart contract wallet will be ignored. This check will be removed hopefully in version 1.133, but for now the check is in place.
- Do not attempt to swap to/from a Taproot address - these will also be ignored. THORChain cannot parse taproot addresses currently. This will be fixed once THORChain hardforks, probably in June or July
Inbound UTXO swaps should have no more than 10 outputs
- Ensure your inbound swaps have the appropriate gas to be immediately included in a block. THORChain vaults rotate every 3 days. If a tx is stuck in a mempool and confirmed after vaults rotate the inbound can be lost. THORChain will attempt to refund inbounds to an inactive vault, but this is best effort and has no guarantee of working.
- Make sure to enforce an appropriate min swap amount. The recommended_min_amount_in value returned from the swap quote endpoint can be used here. This is important, as if swaps are refunded the inbound must be enough to cover the outbound fee of the source chain.
- The Quotes API returns important info for every quote; including “notes” and “warnings”

**Comment by johnnyluo** [comment]
> Do not attempt to swap from an account abstraction or other smart contract wallet. Currently, any smart contract that interacts with THORChain needs to be whitelisted, so any swaps from a smart contract wallet will be ignored. This check will be removed hopefully in version 1.133, but for now the check is in place.

Currently we only allow to swap from and to vultisig address , which is not smart contract address , so I think we are good

> Do not attempt to swap to/from a Taproot address - these will also be ignored. THORChain cannot parse taproot addresses currently. This will be fixed once THORChain hardforks, probably in June or July
> Inbound UTXO swaps should have no more than 10 outputs
We are not dealing with Taproot address either

> Ensure your inbound swaps have the appropriate gas to be immediately included in a block. THORChain vaults rotate every 3 days. If a tx is stuck in a mempool and confirmed after vaults rotate the inbound can be lost. THORChain will attempt to refund inbounds to an inactive vault, but this is best effort and has no guarantee of working.

We currently 1.5x the normal gas for thorchain swap, so should be ok

**Comment by johnnyluo** [comment]
fixed in https://github.com/vultisig/vultisig-ios/pull/467
