### ISSUE TITLE
Maya token send error

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-ios#424]
**Describe the bug**
The user is claiming he is not being able to send Maya Tokens. 

**To Reproduce**
[Steps to reproduce the behavior:
https://discord.com/channels/1203844257220395078/1239008700065386558/1239054622023352390

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by enriquesouza** [comment]
<img width="978" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/1700699/a3ef288a-cde7-449c-8ac2-3cc8546b9cd6">

<img width="988" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/1700699/6f4473fb-ebc7-4072-9c48-7d3b35049db6">

@realpaaao, @johnnyluo , @flypaper0 @Rockindash can you help me to find this error?

**Comment by johnnyluo** [comment]
Are you able to reproduce the issue?

**Comment by enriquesouza** [comment]
> Are you able to reproduce the issue? it could be round error?

I am not. I've tried all kind of ways. Maybe the issue is because they had a previous version, and they probably need to delete the app or just remove the coins, so it can get the latest TokenStore.Coin.

**Comment by realpaaao** [comment]
Removing and adding the Chain solved the problem. Can we automate the check for TokenStore.Coin after new update?
