### ISSUE TITLE
ADD: Keysign/Keygen QR code auto detect

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#436]
# Current

Use main vault camera icon on a key-gen QR code - fail, error message not helpful
Use keygen `JOIN` icon on a key-sign QR code - fail, error message not helpful

# Desired

QR code should have a flag encoded to flip between key-sign and key-gen appropriately

**Comment by Rockindash** [comment]
Will instead implemented a universal scanner for the app since we already have a tag that states if the type is Keysign or Keygen. This way, no additional step is required by the users.
