### ISSUE TITLE
Advanced gas and nonce setting

### ISSUE THREAD

**Issue by SamYap0** [vultisig/vultisig-ios#446]
**Is your feature request related to a problem? Please describe.**
Advanced users would like to set their own gas & nonce settings when sending Tx.

**Describe the solution you'd like**
At minimum, provide the same settings like in Trust Wallet (check the available settings when sending e.g. ETH and BTC)

![IMG_6421](https://github.com/vultisig/vultisig-ios/assets/96066776/4998aafd-35c3-47c9-91c0-b60d7cab7ee7)

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by realpaaao** [comment]
@flypaper0 suggested to just give the options "normal/slow" "fast" "very fast". Won't complicate too much for the user

**Comment by johnnyluo** [comment]
this one has been implemented and released
