### ISSUE TITLE
ADD: Long press feature on Main 

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#449]
Feature to long press in the main menu on icons to re-arrange chains and long press on chain addresses to copy it (like suggested in https://github.com/vultisig/vultisig-ios/issues/399). Therefore we can simplify main menu and make it less cluttered.

Idea:

![image](https://github.com/vultisig/vultisig-ios/assets/167348323/1491bc01-fd9c-4211-8bc3-4daf0e752a2d)

**Comment by Rockindash** [comment]
Duplicate of
https://github.com/vultisig/vultisig-ios/issues/399
