### ISSUE TITLE
Auto remove Tokens when removing chains

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#450]
Problem:
When removing chains with added tokens on the respective chains, the chain can´t be removed automatically. user needs to deselect tokens manually first.
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/cdaba433-7a14-49c2-9e7f-379e5ffb1c26)

Solution
Automatic token removal when removing chain in "Choose Chain"-menu to improve user experience.

**Comment by enriquesouza** [comment]
Fixed
