### ISSUE TITLE
ADD: Sharing of QR code

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#453]
ADD: Possibility to download and/or share QR code for remote signing.

**Describe the solution you'd like**
Add share button on Vault setup page to share/save QR code 

![image](https://github.com/vultisig/vultisig-ios/assets/167348323/ec6096d0-6cbc-44af-832b-b5cb43493777)

**Comment by johnnyluo** [comment]
closing this one in favour #535
