### ISSUE TITLE
ADD: Custom Token selection

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#457]
ADD: Possibility to add Custom Token via Contract address. With autofill NAME, SYMBOL, DECIMALS.

Use Figma as template see here:

![image](https://github.com/vultisig/vultisig-ios/assets/167348323/717e5a8a-615c-4951-9970-2100281ed2aa)

**Comment by johnnyluo** [comment]
It has been implemented https://github.com/vultisig/vultisig-ios/pull/627
