### ISSUE TITLE
Swap explorer/progress links are in some cases broken

### ISSUE THREAD

**Issue by oxyc** [vultisig/vultisig-ios#458]
**Describe the bug**

After performing a swap

1. If the tx fails, there’s still an etherscan link that’s obviously broken.
2. when a tx succeeds the link to follow progress is broken https://runescan.io/tx/Transaction%20already%20broadcasted.

**To Reproduce**
1. Go to perform a swap
3. Click on the tx and/or show progress links on all keysign devices
4. On the device which didn’t broadcast the tx link is available but broken

**Expected behavior**
Ideally links should exist on both devices but should at least be validated so no broken links are shown

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - Version 25

**Comment by johnnyluo** [comment]
This one has been addressed in #479

**Comment by johnnyluo** [comment]
the fix will be in the next build
