### ISSUE TITLE
Switching from and returning to app with fade id reset screen to vault screen

### ISSUE THREAD

**Issue by oxyc** [vultisig/vultisig-ios#459]
**Is your feature request related to a problem? Please describe.**

After performing a swap, the confirmation screen which is shown closes automatically if you open a different app and return. Eg by opening the explorer link it’s impossible to come back and open the progress link

Edit: I guess this applies to all views at least with face id.

**Describe the solution you'd like**

Keep the last view in memory and return to it.

**Comment by realpaaao** [comment]
@enriquesouza @Rockindash 
That feature is needed to be implemented before v1.0 as in every view when exiting the app, it resets to main page.
therefore also when doing a vault creation or swap etc. etc. it is not possible to come back to the point and need to be initated from the start.

**Comment by Rockindash** [comment]
I am currently updating the way FaceID authentication is handled (Issue #427). This should resolve this reset last seen view issue as well.

**Comment by Rockindash** [comment]
Just pushed the fix for the same:
https://github.com/vultisig/vultisig-ios/pull/470

**Comment by johnnyluo** [comment]
I believe this one is fixed,closing
