### ISSUE TITLE
Chain list cut off 

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#468]
Bug: When having all chains activated, the last chain is cut off

**To Reproduce**
1. activate all chains
2. totally scroll down
3. see last one cut off

**Expected behavior**
No cut off

**Screenshots**
<img src="https://github.com/vultisig/vultisig-ios/assets/167348323/14253fd6-0c8b-429a-bb88-6e95423ca452" width=50% height=50%>

**Comment by johnnyluo** [comment]
Tried on my phone , but can't reproduce it
