### ISSUE TITLE
ADD: Extra screen for security when deleting vault

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#471]
ADD: Extra screen when deleting vault to make sure user is aware that he is deleting the vault permanetly and can loose funds.
On Delete screen add checkboxes to acknowledges vault deletion and needs to hold the button for 3 seconds, with visual countdown.
See the design in figma.

![image](https://github.com/vultisig/vultisig-ios/assets/167348323/4ff9ebb2-06da-4d45-8b3c-d39a962c87b3)

**Comment by johnnyluo** [comment]
it has been implemented as part of #614
