### ISSUE TITLE
TC Swaps broken due to missing affiliate address

### ISSUE THREAD

**Issue by oxyc** [vultisig/vultisig-ios#474]
**Describe the bug**

Swaps are broken due to https://github.com/vultisig/vultisig-ios/pull/466 missing affiliate address

Edit: Fix: add `affiliate=vi`

![IMG_1455](https://github.com/vultisig/vultisig-ios/assets/302736/5147b867-55b2-43e4-97a3-70da811dea8c)

**Comment by jpthor** [comment]
Use affiliate=vi pls (Vultisig iOS)

**Comment by johnnyluo** [comment]
This one has been fixed at #477
