### ISSUE TITLE
BUG: Build26 Swap Bugs

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#475]
# Build 26
1) Swap from USDT -> RUNE

# Approval Summary page (main device)

* Estimate Fees Inappropriate
* Checklist inappropriate  (What amount? What hacker? It's an approval)

- [x]  done

![image](https://github.com/vultisig/vultisig-ios/assets/41815753/c1a0cd2d-19be-4805-ab24-2b4151565672)

# Approval Verify (pair device)

* From? To? Amount?
* do something useful

- [x] done
 
<img width="457" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/41815753/4bf64a0d-6bae-4e03-a7a8-700cbe5fe9b5">

# Swap Summary

* Checklist inappropriate  (What amount? What hacker?)

- [x]  done

![image](https://github.com/vultisig/vultisig-ios/assets/41815753/62d25ea4-7da2-445d-89e3-3b919337ce33)

# TX Summary

* Error - "TX Already Broadcasted" causes linking to weird URL
```
https://runescan.io/tx/Transaction%20already%20broadcasted.
```

* Needs ninerealms swap tracker 
* add as tap-able blue link (currently it is white, not blue)
```
https://track.ninerealms.com/05771DA779D0876A65BEC3E07A57141D4A39A1181C93A7619256696BD938CAEA
```

- [x]  done

![image](https://github.com/vultisig/vultisig-ios/assets/41815753/218297d4-4799-4c16-917d-22bb2cdf3c10)

# Inch Swap Failed

* after all that (approval and then swap) it did not swap (Etherscan did not show the swap tx, only approval)
* re-attempted (had to go thru approval and swap again) - it failed

<img width="459" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/41815753/1521a01b-f2a1-4d95-b63e-bdc4dd41f09f">

**Comment by johnnyluo** [comment]
@flypaper0 has all these issues been addressed?

**Comment by flypaper0** [comment]
yes closing
