### ISSUE TITLE
Improvement of "To Asset" on swap page

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#482]
At the moment selection of "to Assets" in [VultisigApp/VultisigApp/Views/Swap/SwapCryptoDetailsView.swift](url) sources coins from `$swapViewModel.coins`, resulting in only able to swap to assets that already were selected in "chain selection"-page.
Resulting in user maybe not knowing a asset exists or when deselceting a asset in chain view, also gets removed in swap page.

Needed:
Change that all available assets in vault are possible to select in the "to asset" dropdown.

**Comment by johnnyluo** [comment]
This should be solved one #478 is implemented

**Comment by johnnyluo** [comment]
This one is fixed , we can add tokens from 1inch api , and also all tokens added is available

**Comment by realpaaao** [comment]
@johnnyluo shouldn't this feature already be on the newest testflight version ? 
As it is still only possible to select chains which are already enabled on ChainSelectionView
