### ISSUE TITLE
IPAD: App crashes with 2/2 Vault on reshare

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#484]
Bug: When created a 2/2 Vault with iPhone and iPad and trying to re-share the vaults. App always crashes on both devices when started with iPhone and joined with iPad.

**To Reproduce**
1. Create 2/2 vault
2. re-share vault
3. initiate with iPhone and pair with iPad
4. App crashes

**Expected behavior**
normal re-share

**Smartphone (please complete the following information):**
 - Device: iPhone 11, iPad
 - OS: iOS17.4.1; iPadOS 17.5
 - Version 27

**Comment by realpaaao** [comment]
Also when re-sharing a 2/2 vault (mac, iphone) and extending with iPad to a 2/3 the keygen times out on iPad and freezes for other devices until aborted.

**Comment by johnnyluo** [comment]
I did a couple times today , and it didn't crash for me , Here is how I do it.
1. iPad pro simulator
2. Iphone 11
3. iPad Pro 
- Create a 2/2 vault , initiated on my ipad simulator , and then joined from my iPhone 11, create vault successfully
- Open just created vault on ipad simulator , and click reshare to initiate reshare process
- open just create vault on iPhone 11 , and click reshare to pair with simulator
- Open iPad pro , create vault , and pair with ipad simulator 
- Choose both i phone 11 , and iPad pro on simulator , and click "start"
-  Reshare success 
I did this process a few times , didn't come across a crash.

I am using iPad simulator as main device , but you are using your iphone , did your iphone(main device) get into sleep mode while you keygen/reshare?

**Comment by realpaaao** [comment]
Iphone did not went into sleep mode. 
I tried the steps you described. Worked without problems. Also created new 2/2 and 2/3 vaults, also no problems re-sharing.
Going back to the 2/2 vault that crashes, re-sharing, crashing again. 
Seems like it is specifically this vault that causes the crash...
