### ISSUE TITLE
BUG: movable bar on PeerDiscoveryView

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#486]
The Network selection bar is movable to left and right.

**To Reproduce**
1. Go to `PeerDiscoveryView`
2. Move Network bar to left and right.

**Expected behavior**
Bar not movable on x-axis

Video:

https://github.com/vultisig/vultisig-ios/assets/167348323/166cbd50-a1c6-4a74-8b82-3fbb78325a4e

**Comment by johnnyluo** [comment]
believe this has been fixed at https://github.com/vultisig/vultisig-ios/pull/487

**Comment by realpaaao** [comment]
I can still do it in the latest pull from main and simulator, also bar is now out of the middle. @Rockindash could you verify pls?

**Comment by realpaaao** [comment]
Same problem on swap page
