### ISSUE TITLE
[Crash] Investigate crash report

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#499]
# Look into crash report

![image](https://github.com/vultisig/vultisig-ios/assets/13535088/9ba80812-0e51-4b07-ac66-ca0f273e1932)

**Comment by realpaaao** [comment]
@Rockindash can we close that issue or do you still want to check something?

**Comment by Rockindash** [comment]
Yes, you can close this one. 
@johnnyluo already fixed it.

**Comment by realpaaao** [comment]
closing as already fixed before
