### ISSUE TITLE
[BUG] Need to show swap provider on swap screen

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-ios#503]
**Describe the bug**
At swap screen , when show up estimate fee , and estimate time , please also show swap provider , Currently it doesn't show swap provider , so there is no way for us to know which route the swap will be going through , is it 1inch or thorchain, no way to know , until we get into verify screen

**To Reproduce**
go to swap screen , and try to do a swap

**Expected behavior**
Swap Provider should be displayed on swap screen

**Screenshots**
![IMG_D7CB822D9929-1](https://github.com/vultisig/vultisig-ios/assets/749608/8a071437-ba4f-4021-b767-517be66ffe61)

**Comment by realpaaao** [comment]
will be fixed in #517

**Comment by flypaper0** [comment]
Closing as duplicate
