### ISSUE TITLE
Close Dropdowns automatically

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#518]
Please close dropdowns when tapping in another field or when selecting another dropdown, e.g. on swap page. Otherwise screens get too filled up.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-05-24 at 14 38 06](https://github.com/vultisig/vultisig-ios/assets/167348323/fb4ccee5-5363-48d2-be3f-f37507f93e79)

**Comment by johnnyluo** [comment]
I suppose sometimes people open the dropdown , and didn't select any coin , just move on, by tap into amount field

**Comment by johnnyluo** [comment]
The issue will be resolved once #604 get implemented , in favour of #604 , and closing this one
