### ISSUE TITLE
[BUG] Mac import image not working for Keygen

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#538]
**Describe the bug**
Always getting the following error whenever trying to upload a QR code for pair on the Mac.
"Failed to decode peer discovery message: The data couldn't be read because it isn't in the correct format."

**To Reproduce**
1. Go to Create a New Vault.
2. Tap on Pair.
3. Upload the QR Code image using the upload options.
4. It shows the incorrect format error.

**Expected behavior**
Should show the verify view and start the Keygen process.

**Screenshots**
<img width="510" alt="Screenshot 2024-05-27 at 4 45 56 PM" src="https://github.com/vultisig/vultisig-ios/assets/13535088/e2689a6b-4652-4fe7-959e-70b016cec4f2">

**Comment by enriquesouza** [comment]
<img width="1037" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/1700699/837791de-3b07-4f7b-bdfe-366dfa9b2099">

**Comment by johnnyluo** [comment]
> <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/1700699/335559490-837791de-3b07-4f7b-bdfe-366dfa9b2099.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIwOTYsIm5iZiI6MTcxNzY1MTc5NiwicGF0aCI6Ii8xNzAwNjk5LzMzNTU1OTQ5MC04Mzc3OTFkZS0zYjA3LTRmN2ItYmRmZS0zNjZkZmE5YjIwOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDUyOTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTVlOGNjZTUyMWZjMTEwNjdmMzVhYjkxZTMxYWMwNDYwMzgyOGQ4YzI1NDBmZThmYjY4ZGE2OTdkMDY2MzBkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m3lQmxBeth-RbRjGc2dz7SbizHoNLJ5UzPH2KqxdoeU">

Can you explain what is it?

**Comment by johnnyluo** [comment]
Double checked this one , and it has been fixed
