### ISSUE TITLE
BUG: after failed tx every keysign will fail

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#547]
BUG: When a keysign fails all further keysigns can't be initiated until the apps gets restarted. 

**To Reproduce**
1. failed keysign
2. initiate new tx
3. try to sign new keysign

**Expected behavior**
new keysign initiates without restarting app

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/cfd04f24-99a0-493d-b487-45dd67e362ff)

**Desktop (please complete the following information):**
 - OS: 14.5
 - Version 26

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 17.4.1
 - Version 26

**Additional context**

**Comment by johnnyluo** [comment]
I am having a very hard time to reproduce it , any more context can you provide for this one? @realpaaao

**Comment by realpaaao** [comment]
@johnnyluo could relative consistently reproduce it when initiating a keysign and aborting it directly. After that pairing device was just waiting on keysign to start. Maybe got fixed due to other fixes? 
Will try to reproduce again and come back to you

**Comment by realpaaao** [comment]
Closing, can't reproduce anymore
