### ISSUE TITLE
BUG: keygen/keysign fails with imported vaults

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#552]
**Describe the bug**
All imported vaults fail to keysign or keygen. Tried all setups and pairing, e.g. initiated from either Iphone, mac or ipad.

**To Reproduce**
1. import old vault
2. do keygen/keysign
3. See error

**Expected behavior**
Should exit without error

**Screenshots**
![Reshare](https://github.com/vultisig/vultisig-ios/assets/167348323/5dd5b634-1002-41cd-a58d-0a8aa05786cb)
![signing](https://github.com/vultisig/vultisig-ios/assets/167348323/1953e8e3-4f35-4cd1-b211-bec93d24c809)

**Desktop (please complete the following information):**
 - OS: 14.5
 - Version 26

**Smartphone (please complete the following information):**
 - Device: iPhone, Ipad
 - OS: 17.4.1
 - Version 26

**Additional context**
It only happens with imported vaults, newly created ones function without problem.

**Comment by johnnyluo** [comment]
This is because of reshare , one backup is before reshare , and second backup is after reshare , thus they are not on the same keygen committee , thus can't work together to sign transaction.

Probably only thing we should do is , ask user to backup their vault shares after reshare.

**Comment by realpaaao** [comment]
Not a bug. We just need to emphasize this in the documentation
