### ISSUE TITLE
[BUG] wrong view after leaving camera view

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#563]
**Describe the bug**
When leaving the  `camera view` the app switches to `joinkeysignview ` and keeps buffering

**To Reproduce**
1. open camera
2. go back
3. See error

**Expected behavior**
go back to `homeview`

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/48f23182-f521-4df5-a776-5f31e034b69b)

**Smartphone (please complete the following information):**
 - Device: iphone11
 - OS: 17.4.1
 - Version 26

**Comment by Rockindash** [comment]
Fixed under PR #577 
https://github.com/vultisig/vultisig-ios/pull/577
