### ISSUE TITLE
[BUG] crash when using exisitng vault name in vault creation

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#565]
**Describe the bug**
When creating a new vault with a name that already exists, the initiating device crashes while the pairing device creates the vault.

**To Reproduce**
1. Create vault with existing name
2. do keygen
3. app crashes

**Expected behavior**
Check on Vault creation in `RenameVaultView` if vault name already exists, if prompt user an error message to change vault name.

**Comment by johnnyluo** [comment]
Let's make sure the vault name is unique

**Comment by realpaaao** [comment]
@Rockindash solved this issue with 1890dedda4fbc3b3b32415785ccfecd4991a889e . Thanks!
