### ISSUE TITLE
[BUG] 2nd consecutive re-share crashes vault

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#567]
**Describe the bug**
In an 2/2 vault, after the 2nd consecutive re-share the vault will crash and not able to re-share again possibly due to difference in Vault shares.

**To Reproduce**
1. Create Vault
2. re-share 1st time
3. directly re-share 2nd time
4. Vault crashes

**Expected behavior**
consistent re-share

**Smartphone (please complete the following information):**
 - Device: iPhone, iPad
 - OS: 17.4.1
 - Version 26

**Additional context**
See discord for vault shares

**Comment by johnnyluo** [comment]
I can't reproduce this error , I did the following
1.Create 2/2 vault
2. Reshare to create a 2/3 vault ,  first reshare
3. Reshare to remove the newly added device, become a 2/2 vault , second reshare
4. Reshare to add another device , become a 2/3 vault , third reshare
There is no crash
