### ISSUE TITLE
[BUG] sending same amount of tx after its completion

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#570]
**Describe the bug**
After the completion of a tx and you immidiatlely try to send another tx without refreshing, the wallet shows the old balance and it is possible to send a tx with an amount higher than actually in the wallet, resulting in invalid tx.
[failed tx](https://runescan.io/tx/BA24D51DD21FF79F97A0B7B0B208D0BE7FE8D01A40DE4BD5FAE6EDEAA101C1C6)

**To Reproduce**
1. do a tx
2. after completion directly do another tx without refreshing
3. try selecting the max amount of asset and send

**Comment by enriquesouza** [comment]
As discussed, we will close this issue, since the balance comes from the blockchain after its confirmation. Nothing we can do about it rn.
