### ISSUE TITLE
[BUG] No Chain Selected message bug

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#580]
**Describe the bug**
No Chain Selected message shows up for some time then goes away.

**To Reproduce**
1. Create a Vault.
2. Tap on ChainCell.
3. Go back.
4. You will see the error message and it'll go away soon.

**Expected behavior**
That message should show up only when no chain is selected for that vault.

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/13535088/77fbdd97-700c-4c0e-a1d8-aca8f7f43b7e)

**Aditional note**
This is being caused by setting up default coins for new Vaults. For some reason, the coins go away on Vault disappear and has to be assigned again on appear.

**Comment by johnnyluo** [comment]
I believe this one get fixed as well , but user can manually remove all the chains , then this message will show up
but I guess that's intended behaviour

**Comment by johnnyluo** [comment]
close
