### ISSUE TITLE
ADD: An extra Vault share without pubkeys

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#583]
Please implement a "Family-Share" where the public keys are removed in the vault share, so a user can share and backup his vault with "family and friends" without them seeing the balances of the user.
After a user has successfully backed up or shared their vault, let them automatically return to the main home view.

**Comment by johnnyluo** [comment]
Maybe we can just https://github.com/vultisig/vultisig-ios/issues/443 , when user backup a vault share with a password, then the content will be encrypted , then user can share it with their family and friends
If they don't want family and friends to see the balance , then don't share the password

**Comment by realpaaao** [comment]
@johnnyluo but technically not possbile, correct?

**Comment by realpaaao** [comment]
Will be included with the QR vault share on #849

**Comment by johnnyluo** [comment]
I think we can close this one now @realpaaao agree?

**Comment by realpaaao** [comment]
close as completed
