### ISSUE TITLE
[BUG] No default tokens selected after vault import

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#588]
**Describe the bug**
When opening a vault the first time after import, no chains are selected.

**To Reproduce**
1. Import a vault
2. Switch to vault
3. See error

**Expected behavior**
default chains get displayed

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/28586c40-7238-49f6-88c2-b96e6fc5306f)

- All devices versions 27

**Comment by realpaaao** [comment]
@Rockindash I guess it is same problem/duplicate as in #580

**Comment by johnnyluo** [comment]
fixed in https://github.com/vultisig/vultisig-ios/pull/593
