### ISSUE TITLE
[BUG] MAC can't initate keysign on WIFI

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#589]
**Describe the bug**
It is not possible to initiate a keysign from MAC, the pairing devices waiting for keysign to begin. 
When selecting `Cellular` devices can join keysign.

**To Reproduce**
1. create keysign on mac
2. select `Wifi`
3. try to pair with other device

**Expected behavior**
Other devices can pair when Wifi selected

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/60fa6f36-4f05-4d1b-99c8-f33d3199c990)

**Desktop (please complete the following information):**
 - OS: [4.5
 - Version 27

**Comment by realpaaao** [comment]
Also happens on keygen

**Comment by johnnyluo** [comment]
I just tried on my Mac , I can initiate keygen & Keysign just fine , I am going to close this one , as this is mostly like related to the local WIFI network , which doesn't allow mDNS, cause apple's bonjour service doesn't work.  There is nothing we can do about it.
There are two options user to get around it.
1.  User can use their phone as wifi hotspot , and connect mac to their phone , this way , wifi/hotspot version will work
2. Choose Cellular option
