### ISSUE TITLE
[BUG] Removing all chains, still displays tokens

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#591]
**Describe the bug**
If all chains get removed in `ChainSelectionView` while having Tokens enabled in any chain, will still display the chain with the icon of the enabled token.

**To Reproduce**
1. Deselect all chains on `ChainSelectionView`
2. Return to HomeView
4. See still enabled Tokens

**Expected behavior**
Tokens of each chain get automatically removed like proposed in #450 

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/b252e32f-3424-4f6f-8964-751ff6f32dd4)
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/030d73c4-a283-4691-b651-476d4b1cee49)

**Comment by johnnyluo** [comment]
This one is the same as #450

**Comment by enriquesouza** [comment]
We fixed it in the same PR as the auto-discovery tokens.
