### ISSUE TITLE
[BUG] Vault balance not displayed after import/update

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#592]
**Describe the bug**
After the latest update, importing a vault will not display dollar value of assets in vault until the vaults get switched.

**To Reproduce**
1. import vault
2. See error, no $ balance displayed
3. switch to different vault
4. switch back to imported/updated vault
5. See balances

**Expected behavior**
dollar value gets displayed automatically without the need to switch vaults

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/97f2b53c-2a01-4cad-ac07-da556d8d3f0f)

**Comment by johnnyluo** [comment]
fixed in
