### ISSUE TITLE
[BUG] After did a keysign successfully, if I switch to another app, and then go back in again , it open's join keysign view

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-ios#594]
**Describe the bug**
After I did a keysign successfully, I go back to main screen,  then I move on to other things , leave the phone there , didn't do anything , then next time I open vultisig , it open's join keysign view

**To Reproduce**
1. Create a transaction by sending some fund to an address
2. Join keysign on your secondary device
3. Keysign successful , and click "complete" to go to home screen
4. lock your phone 
5. unlock your phone 
6. Open vultisig , authenticate with face id
7. Vultisig goes to Join Keysign screen

**Expected behavior**
Vultisig should goes to home screen , open the vault I used last time

**Screenshots**
![IMG_5F7E3AB86550-1](https://github.com/vultisig/vultisig-ios/assets/749608/11f1435d-b192-4a25-b706-878ca97cb6c4)

**Comment by realpaaao** [comment]
Also happens when just locking the device
