### ISSUE TITLE
ADD: Ability to get quotes for swap without funds

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#596]
**Is your feature request related to a problem? Please describe.**
It would be nice for the user to be able to qoute swaps even when no or not enough funds are in the wallet.
Giving more transparency before doing a swap.

**Comment by flypaper0** [comment]
@realpaaao we doing it for 1inch swaps, but thorchain API returns error when balance is insufficient

**Comment by realpaaao** [comment]
@flypaper0 how does Thorswap display it ? As it is possible there.

**Comment by johnnyluo** [comment]
This one has been fixed in main , as I can specify an amount over my balance to check swap quote
