### ISSUE TITLE
[BUG] tx already exists when sending ERC-20

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#597]
**Describe the bug**
When sending ERC-20, mostly tried USDT, the pairing device often gets the `transaction already exists` occasionally occurs also on pairing device.

**To Reproduce**
1. send ERC-20
2. See error

**Screenshot**
<img width="509" alt="tx already exists" src="https://github.com/vultisig/vultisig-ios/assets/167348323/5a0ec417-7fdb-4885-9200-5e1c122c868f">

**Expected behavior**
seeing tx hash consistently on both devices

- Version 27

**Comment by realpaaao** [comment]
@johnnyluo still getting this error from time, sometimes initiating or pairing device. Should be resolved in v29?

**Comment by realpaaao** [comment]
reopening due to having that error ~ every second tx. Either on initating or pairing device but never on both simultaneously

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/729

**Comment by enriquesouza** [comment]
@johnnyluo and @realpaaao it was a white space causing this.

**Comment by johnnyluo** [comment]
Closing , as it should been fixed , please reopen it if it still exist
