### ISSUE TITLE
[BUG] Main balance gets dropped

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#600]
**Describe the bug**
After restarting/opening app the total balance gets dropped. Personally only could recreate with mac and ipad but users also reported it on iphone.

**To Reproduce**
1. close app
2. reopen
4. See total balance get dropped

**Expected behavior**
Total balance gets displayed correctly

**Desktop (please complete the following information):**
 - OS: 14.5
 - Version 27

**Smartphone (please complete the following information):**
 - Device: Iphone 11
 - OS: 17.5.1
 - Version 27

**Comment by realpaaao** [comment]
@flypaper0 noticed that error popping up in the console, could that lead to whole balance getting dropped?

<img width="572" alt="rpc error" src="https://github.com/vultisig/vultisig-ios/assets/167348323/1db91fc9-85d6-4470-b4f1-ff6341dcbc70">

**Comment by johnnyluo** [comment]
This one can't be reproduced on main branch , it could be fixed in https://github.com/vultisig/vultisig-ios/pull/593

Closing
