### ISSUE TITLE
[BUG] Symbols possible in send page

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#615]
**Describe the bug**
On iPad and Mac it is possible to enter any symbol wanted in the amount field.

**To Reproduce**
1. Go to SwapView
2. Enter Letters or Symbols in `Amount` field
3. See error

**Expected behavior**
Restrict symbols and letters, only numbers.

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/5618264b-d0e9-4b3b-9f2b-1d9bf75e8e0b)

Devices: iPad, Mac
 - Version [28

**Comment by johnnyluo** [comment]
Closing , as currently next button will be disabled
