### ISSUE TITLE
ADD: Possibility to hide balances

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#629]
Please add a possibility to hide balances according to Figma design. Change the `Eye` icon if toggled, like in figma.
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/34affb37-cde4-4a50-a39d-1786f8f99f61)

**Comment by johnnyluo** [comment]
Hide the total balance works fine , but it seems to me , when user want to hide balance , they mean to hide all the balances from each individual chain as well

**Comment by Rockindash** [comment]
@johnnyluo just pushed the fix. Can you review it again??
https://github.com/vultisig/vultisig-ios/pull/635
