### ISSUE TITLE
[BUG] app switches vault after going back from chaindetailview

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#630]
**Describe the bug**
When going into `ChainDetailView` after switching the vault and going back to `HomeView`, The vault switches back to the before selected vault

**To Reproduce**
1. Select different vault
2. Enter `ChainDetailView`
4. Go back to `HomeView`
5. See error

**Expected behavior**
Stay in the selected vault

Affected devices:
iPhone and iPad on version 28

**Comment by realpaaao** [comment]
@Rockindash @johnnyluo could be related to #594 as I only can reproduce it on v28 but not on `main`, I'd say we leave it open until I can confirm on new testflight version.

**Comment by Rockindash** [comment]
@realpaaao yes it is. You can close this issue since this has been fixed.

**Comment by realpaaao** [comment]
closeing as resolved in #594
