### ISSUE TITLE
[BUG] ETH send max button doesn't work

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#643]
**Describe the bug**
When trying to send the Max amount of wallet balance with the `max button`, different error messages (see screenshots) occur but never able to send amount. Apart a user reported that he could sent a tx with amx amount but never went out of wallet.

**Expected behavior**
Improve calculation that max send is possible

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/c534e78a-d3cc-45d8-bd48-c6fcda22a57e)
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/ff723d5d-2948-4e02-829c-e24efdd10cec)

all versions 29

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/745
