### ISSUE TITLE
[BUG:IPAD] First import after install crashes app 

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#645]
**Describe the bug**
When installing the app and doing the first import, it crashes the vault. Furthermore after restarting,with this first imported vault it is impossible to select ETH chain, always ends in crash. Even after deleting the affected vault and importing it again ends in crash.
Affected vault does not have default chains displayed after restarting app
Possible to reproduce with any vault who gets imported first after install. 

**Expected behavior**
normal import 

**Smartphone (please complete the following information):**
 - Device: iPad 9th gen
 - OS: 17.5.1
 - Version 29

**Additional context**
see testflight crashes.

**Comment by johnnyluo** [comment]
Can't actually consistently reproduce this one , thus closing this for now , feel free to reopen it once we can consistently reproduce it
