### ISSUE TITLE
IMPROVE: Token selection screen 

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#646]
At the moment when selecting a token the whole 1inch token list gets displayed and it is hard to find the correct tokens.

Like @flypaper0 already proposed in discord, we should add two sections:

- [x] group already selected tokens on top
- [x] group possible tokens below, where they are sorted after mcap to display relevant tokens first, also when searching for tokens.

![image](https://github.com/vultisig/vultisig-ios/assets/167348323/2aa4c9a0-8ad0-4df5-b2c0-0f0507c88d3e)

**Comment by johnnyluo** [comment]
done
