### ISSUE TITLE
ADD: Possibility to also browse files on camera

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#652]
When pairing to do keygen/keysign, please add file picker so it is possible to browse files and pictures. Like that it is possible to do keygen/keysign with shared QR codes and user has full flexibility.

Reason: If a user sharse a QR over airdrop from iPhone/iPad the files can't be imported into the app as the photo gets save in downloads and with the button we just have access to the gallery.

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/755
