### ISSUE TITLE
[BUG:IPAD] stuck in keygen w/ QR code share

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#653]
**Describe the bug**
When pairing iPhone and iPad over QR share, the iPad gets stuck in EdDSA gen step occasionally(around 1 out of 3 times).Noticed it as first time QR share the iPad got stuck. I couldn't narrow it down completely but mostly happens when iPad is pairing device.

**To Reproduce**
1. Create vault
2. Share QR code to pair
3. start keygen

**Expected behavior**
A consistent keygen with QR code share

**Smartphone (please complete the following information):**
 - Device: iPhone, Ipad
 - Version 29

**Comment by johnnyluo** [comment]
This might be a bug in the tss-lib itself , sometimes it fail to emit the last message , and I notice it mostly happen with 2/2 vault creation, need to investigate it

**Comment by realpaaao** [comment]
@johnnyluo can't recreate atm. closing until surfaces again
