### ISSUE TITLE
ADD: more settings to backup file

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#657]
So that the user can have a seamless experience when importing a vault, please add:

- [ ] language
- [ ] currency
- [ ] chains/tokens (can be skipped when autodetect is implemented)

**Comment by johnnyluo** [comment]
Language & Currency is on the app level , not on vault level , so it is not relevant to chains/tokens

**Comment by realpaaao** [comment]
Closing due to unrelevance
