### ISSUE TITLE
[BUG] Keysign discover instability on mac

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#661]
**Describe the bug**
Occasionally it is impossible to start a keysign as the pairing device keeps waiting for the signing process to begin. It roots from Mac when the app stays open for a long time. Could it be a timeout problem? As a restart of the app on the initiating device fixes it.

**Expected behavior**
Consistent keysign initiation

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/f133f2cd-8330-493d-90f7-0a01169185cc)

- Version 29

**Comment by realpaaao** [comment]
@johnnyluo it happens quite consistent  for me, after having app open for around ca. 5 minutes.

**Comment by realpaaao** [comment]
@johnnyluo When looking in console on mac, it looks like it cycles this message. noticed that this also happens when intenting a 4/5 with two androids included... 

<img width="1266" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/167348323/8fd8bb8a-4cc2-4193-a1f6-696387178bf5">
<img width="1246" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/167348323/7573dea6-4a7a-4cb2-b20a-80fb6ebcd4b1">
<img width="1246" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/167348323/86a213bc-0a35-4e4a-9fdf-7bee56db27f1">

**Comment by realpaaao** [comment]
@johnnyluo I still have those problems on macOS version and need to restart from time to time... Not sure what's causing it

**Comment by realpaaao** [comment]
@johnnyluo I just have that now from time to time on my iPad. Not sure whats causing it. Just documenting so we keep track.

**Comment by johnnyluo** [comment]
Will close it for now , can't actually reproduce it reliably
