### ISSUE TITLE
ADD: prefix check on keygen

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#668]
If doing a keygen we should add logic to check for the prefix and if user already did an expansion and contraction of the vault, i.e 2/3 to 2/2 or later if used by bigger groups like funds, that the pairing device with another prefix gets an error and can't join keygen. 
At the moment the device joins and the user doesn't know why the keygen is not successful.

note: will add error view on figma

**Comment by johnnyluo** [comment]
I am confuse about this one , when keygen , prefix is always empty

**Comment by realpaaao** [comment]
@johnnyluo was thinking for reshare, which is also the normal keygen. Or am I wrong and it is a separate ceremony?

**Comment by johnnyluo** [comment]
I suppose we could add a check , if user trying to join a reshare with an old vault , which is not suppose to ( the one party that had been kicked our during last reshare)

But this is a quite edge case same as #669 , we could add it later.

**Comment by realpaaao** [comment]
agree let's add it later when more resources are available.

**Comment by realpaaao** [comment]
closing as we have prefix in vault shares.
