### ISSUE TITLE
[BUG] Can't join keygen after reshare

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#669]
**Describe the bug**
When creating a 2/3 vault, resharing it to 2/2 and trying to reshare it again to 2/3 with the same devices it is not possible. The earlier kicked out device gets `resharing key failed` error.
Possibly due to #668 missing logic.

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/1b3c6b2f-1010-4936-b03d-a407fed22c4a)

-Version 29

**Comment by johnnyluo** [comment]
@realpaaao  , how did you join the reshare process on the "reuse" device?  
I image the process should be like the following
1. Make sure the previous vault has been deleted 
2. "Create vault" , "Pair" 
This didn't work?

**Comment by realpaaao** [comment]
@johnnyluo These steps work:

> 1. Make sure the previous vault has been deleted
> 2. "Create vault" , "Pair"
>    This didn't work?

but I was thinking for non technical people and as no indication is given, they maybe will not delete it and try again with the old vault still installed... 
Edge case but I think we should consider everything and optimize for it?

**Comment by johnnyluo** [comment]
That will fail , the vault won't be able to save, because they got two vaults with the same public key ,  that's even more confusing

**Comment by realpaaao** [comment]
Can we detect if a user removed a device and display a message that the removed vault should be deleted? I guess too resource intensive atm or we just amend the docs...

**Comment by johnnyluo** [comment]
We could remove the vault as soon as the reshare is done , but I think in some cases that user might want to keep it as watch only

**Comment by realpaaao** [comment]
agree, auto remove would not be the best. I think if we amend the docs that should be suffcient as when Qs arise we can forward to that section.

**Comment by realpaaao** [comment]
closing as amending docs will be sufficient.
