### ISSUE TITLE
Tx History

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-ios#671]
We would need to add back the tx history

**Comment by johnnyluo** [comment]
It is nice to have feature , we don't want to add it right now , as a lot blockchain doesn't provide this feature , and we will have to pay a third party to get access to it , or alternatively we have to implement the scanner and tx history index ourselves ,  One day when we have enough resource , maybe , but definitely not now

**Comment by enriquesouza** [comment]
I will close this for now. Otherwise, we will have to add all of them. Each of them has a different API provider for this, and it will be complicated and expensive to add it, in my opinion.
