### ISSUE TITLE
[BUG] UTXO chains max send

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#690]
**Describe the bug**
When using the max send on UTXO chains it is possible to exceed wallet balance + fees when clicking on the `max` button a second or third time.

**To Reproduce**
1. Go to any UTXO chain
2. Click on send
3. Click on `MAX`
4. Click on `MAX` a second time
5. See error

**Expected behavior**
Consistent calculation of possible send amount no matter how many times clicking `MAX`

**Screenshots**
https://github.com/vultisig/vultisig-ios/assets/167348323/3ca24540-0859-4763-8374-250d8443d904

-version 29

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/745
