### ISSUE TITLE
[BUG] Various Chains not able to use MAX send

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#691]
**Describe the bug**
With various Chains it is not possible to use the `max send` button:

- [ ] AVAX
- [ ] OPTIMISM
- [ ] BSC

**Expected behavior**
Possible to use the `max button` functionality 

**Additional context**
For the L2 it is the same error as in #643 for ETH. Possibly more L2 are affected.

For BSC, BNB send it is possible due to a wrong gas amount usage and calculation. On iOS it prompts 2.5 GWEI and on android it prompts 1.5 GWEI.

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/745
