### ISSUE TITLE
[BUG:MAC] Swapping ERC-20 blocks changing to asset

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#699]
**Describe the bug**
On Mac: When opening the `swap view` and trying to swap from an ERC-20, tried with USDT and USDC, to another available route it is not possible to change the `to asset` until switching the assets or the input. See video for reference

**To Reproduce**
1. Go to Swap view
2. Select USDT or USDC
3. Select available swap route

**Expected behavior**
Able to change `To asset`

**Screenshots**

https://github.com/vultisig/vultisig-ios/assets/167348323/b2651ecb-acf4-45c7-ac52-965e5887c49b

**Desktop (please complete the following information):**
 - OS: 14.5
 - Version 30

**Comment by johnnyluo** [comment]
fixed by https://github.com/vultisig/vultisig-ios/pull/704
