### ISSUE TITLE
[BUG] instabilities after importing vault shares

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#706]
**Describe the bug**
When importing a encrypted vault share the vault behaves strangely.
Able to crash after vault import, not load default chains, crash after selecting certain chains (issue #703), or chains not selecting when toggleing

**To Reproduce**
1. create vault or use old one
2. export vault 
3. import
4. See described error

**Screenshots**

https://github.com/vultisig/vultisig-ios/assets/167348323/02dce86a-78a3-4bce-82ac-e563b8fac5a0

all devices version 31

**Comment by realpaaao** [comment]
https://github.com/vultisig/vultisig-ios/assets/167348323/44dd52dc-77f7-467c-b5f6-7e006154db25

https://github.com/vultisig/vultisig-ios/assets/167348323/4747a170-b835-4a44-aca3-d2e08c0b2d98

**Comment by johnnyluo** [comment]
Can't be reproduced , after recent changes from Coin -> CoinMeta
