### ISSUE TITLE
[BUG] Some ERC20 tokens has wrong rates 

### ISSUE THREAD

**Issue by flypaper0** [vultisig/vultisig-ios#707]
**Describe the bug**

<img width=300 src="https://github.com/vultisig/vultisig-ios/assets/5384197/83860c33-d57d-4923-ac2d-c4729b5def5b">

**Comment by enriquesouza** [comment]
@flypaper0 and @realpaaao we removed the coingecko ids. So it should be fixed now.

**Comment by johnnyluo** [comment]
Closing , if it still exist , please reopen it
