### ISSUE TITLE
IMPROVE: GAS fees congruent with iOS

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#711]
Android and iOS have general different gas fees calculation. Please verify which is off.
@yvebe mentioned it is probably on android.
Keep it open here until verified which is off and which can be improved

**Comment by enriquesouza** [comment]
What is the difference? I see it is showing in GWEI for EVMs like we are doing.

**Comment by realpaaao** [comment]
@enriquesouza there was a time where it was not congruent. But could be that it now is. If you say they are equal we can clos the issue.

**Comment by johnnyluo** [comment]
Closing
