### ISSUE TITLE
IMPROVE: Dropdowns double icons

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#719]
To have a nicer UI please remove the currently selected Chain/Token from the dropdown to not have it displayed twice.

![image](https://github.com/vultisig/vultisig-android/assets/167348323/a3132426-8a6a-4e07-af86-212517f3ac7b)

**Comment by realpaaao** [comment]
This is not needed if #604 is implemented

**Comment by johnnyluo** [comment]
Closing , dropdown has been changed to a separate screen
