### ISSUE TITLE
[BUG] Not able to swap on TC route from $RUNE

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#722]
**Describe the bug**
Not able to create QR code(go to pairing view after verify) when trying swap `from` $RUNE `to` any asset over Thorchain route.
When trying to swap TO $RUNE it works normally.
When going back to Swap view the error `unexpected swap error` gets promted

**To Reproduce**
1. Open Swap View
2. Select $RUNE as `FROM` asset
3. select `TO` any asset over TC route

**Expected behavior**
able to swap from RUNE

-version 31

**Comment by johnnyluo** [comment]
@realpaaao can't reproduce this one on the latest version , please double check
Please close if you can't reproduce as well

**Comment by realpaaao** [comment]
@johnnyluo yes, I can still reproduce it.
