### ISSUE TITLE
[BUG] Password prompt when importing other files

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#730]
**Describe the bug**
When trying to import other files than viable .dat files, you always get the password input prompted.

**Expected behavior**
Check if viable .dat file is imported and if not give an appropriate error `Please select a viable file type`

**Screenshots**
<img width="1005" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/167348323/39c036fd-8501-456b-b297-21efaccfc806">

**Additional context**
I would also amend the UI Screen to display that only .dat files are viable to upload.

**Comment by realpaaao** [comment]
@Rockindash do we have `upload files, text or image` prompted on purpose?
As I think we only can use .dat files as input.

**Comment by johnnyluo** [comment]
This should have been fixed in https://github.com/vultisig/vultisig-ios/pull/744
