### ISSUE TITLE
[BUG] Crashing vault when re-sharing

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#738]
**Describe the bug**
When resharing to a device that already has the name `Main Vault` the app on the respective newly integrated device crashes and produces the same error as in #737. Probable as re-sharing the new device gives the vault a static name `Main Vault`.

**To Reproduce**
1. reshare a exsisting vault
2. join with a device that already has vault named `Main Vault`
3. complete keygen

**Expected behavior**
paired device does not crash

**Additional context**
@johnnyluo would it be possible to pass the name of the re-shared vault to the newly integrated device? So than this error could be negated and an improvement on [android](https://github.com/vultisig/vultisig-android/issues/435) would be possible.

**Comment by johnnyluo** [comment]
fixed in #751
