### ISSUE TITLE
IMPROVE UI: Make Views scrollable if keyboard is enabled

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#743]
Please make all views scrollable if the keyboard is enabled as it is possible that on some views content gets blocked by the keyboard.

for example in `send view` the USD amount
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/cc1f6efd-4bc9-4de4-82eb-016769f37128)

**Comment by johnnyluo** [comment]
It is already scrollable , I can scroll it when my keyboard is up
