### ISSUE TITLE
[BUG] Not able to deselect Keyboard in TokenView

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#747]
**Describe the bug**
When adding a token and opening the `TokenSelectionView` the search bar is always selected and the keyboard enabled without the possibility to close. therefore some of the screen and repectively some tokens are blocked and it is needed to scroll. 

**To Reproduce**
1. Go to `tokenselectionview`
2. Click on add token
3. See error

**Expected behavior**
able to close the keyboard

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/e0bf23dd-c845-4544-a6f5-4913a6e7ccf2)

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: 17.5.1
 - Version 33

**Comment by johnnyluo** [comment]
There is a `next` button on the keyboard , which will close the keyboard
