### ISSUE TITLE
[BUG:iPad] Crashing vault on import

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#748]
**Describe the bug**
When. importing a vault on iPad, the app crashes. After restarting the app the default app never get displayed correctly. Either no Chain is selected or just on.

**To Reproduce**
1. import share on iPad
2. See error

**Expected behavior**
able to import vault share without crash

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: 17.5.1
 - Version 33

**Comment by johnnyluo** [comment]
Can't be reproduced anymore , please reopen it if you can
