### ISSUE TITLE
ADD: UTXO management for BTC

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#773]
_THIS IS ONLY FOR DOCUMENTATION AND STAYING AWARE OF THE FEATURE AT THE MOMENT_

We should add UTXO management and consolidation to Bitcoin. As this will be an important feature in the coming years to ensure access to small UTXOs in the bitcoin wallet.

**Comment by jpthor** [comment]
All UTXOs are swept into 1 everytime you make a tx
