### ISSUE TITLE
ADD: Default chains in settings

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#781]
Please add the possibility to override the hardcoded default chains in the settings and make them global for all vaults that get created. Include all supported chains.
If user deselects all default chains, enforce the hardcoded chains.

Use [Figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=6892-6496&t=xfnbvFHmouveBm9k-4) as reference.

**Comment by johnnyluo** [comment]
fixed #947
