### ISSUE TITLE
[BUG] Vault changes after rename

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#802]
**Describe the bug**
When changing vault name, the vault changes.

**Expected behavior**
After rename, the amended vault is still selected in `Home View`

-version 35

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/assets/1700699/8b306b61-680b-4098-99f6-2850533eca3e

@realpaaao can you show me what are you expecting?

**Comment by realpaaao** [comment]
@enriquesouza It happens when going directly from home view into settings. 

https://github.com/vultisig/vultisig-ios/assets/167348323/a472eed8-3eec-441e-990e-f81c9db4f4a8

**Comment by enriquesouza** [comment]
It does not happen to me, maybe it is because I don't have as many wallets as you do.

**Comment by enriquesouza** [comment]
Found it, if you have more than 2 wallets it happens

**Comment by johnnyluo** [comment]
This is because the selected vault's name has been saved , but since the name get changed , so it doesn't match with the saved vault name
