### ISSUE TITLE
[BUG] Selecting other asset in Send view don't change from address

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#814]
**Describe the bug**
on main branch: When opening `Send view` and changing the `From` asset doesn't change the the address. 

**Expected behavior**
Changing address to the respective selected chain

**Screenshots**
<img width="313" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/167348323/9e123ca1-c0fc-44bc-a370-1d68cb79cb8d">

**Additional context**
on main branch

**Comment by johnnyluo** [comment]
fixed in #821
