### ISSUE TITLE
ADD: Sorting on Token view 

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#833]
Currently the token view only has hardcoded tokens on display.

Please make the view dynamic that orders the view so the top 20 tokens by mcap of the respective chain are displayed and the rest can be discovered over the search function.
Therefore the user will see the most important tokens by default and can select the rest

**Comment by enriquesouza** [comment]
Please, list for me per chain in a spreadsheet the coins and tokens you prefer to be defined as default. Thanks )

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/1014
