### ISSUE TITLE
ADD: Swap view only displays tokens with balance

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#834]
At the moment the swap view is generic to all chains, leading to that only enabled tokens can be sent.

With the auto discovery feauture this can be improved that only tokens with balance are displayed and able to be sent. This can be done after #750  is implemented.

**Comment by johnnyluo** [comment]
This is not correct , for example , I don't have any USDT , but I would like to swap some RUNE to USDT, if we only display tokens with balance , then USDT won't show up on the list , I won't be able to swap it.

I still rather user add the token first , and then swap from/to it

**Comment by realpaaao** [comment]
Yo are right, also with #604 it will be improved.
