### ISSUE TITLE
IMPROVE: 2-3 Vault Setup 

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#838]
At the moment it doesn't matter if 2-3 setup is initally selected on the setup selection screen, when only added a second device it shows 2-2 and the user is able to proceed. 
This can confuse the user and it should be improved.

Please improve that on selected 2-2 and 2-3 setup the user is only possible to proceed/auto proceed when the `n`-amount of devices is present and selected, while `m`-`n` stays dynamic .

![image](https://github.com/vultisig/vultisig-ios/assets/167348323/cd711564-90c7-4a1e-9d6a-3099501a6539)

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/897
