### ISSUE TITLE
[BUG] Native token doesn't get updated consistently on send view

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#846]
**Describe the bug**
In send view when switching between tokens of different chains the native token balance doesn't get updated consistently.

**To Reproduce**
1. Go to send view
2. select token
3. change on token to another token on another chain

**Expected behavior**
Native token balance gets updated consistently 

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/1d792548-5a2b-495e-8470-f10bc171eb06)

-version 37

**Comment by enriquesouza** [comment]
It does change the balance, but takes a while. I will try to add a loader.

https://github.com/vultisig/vultisig-ios/assets/1700699/40a30811-7533-4446-8f3c-5ee0a23bab79

**Comment by enriquesouza** [comment]
this should fix the error and some others

https://github.com/vultisig/vultisig-ios/assets/1700699/a651db35-a4ef-4ad1-9cee-8f8185a46ed9
