### ISSUE TITLE
ADD: Sharing Vault UID via QR for web

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#849]
As @johnnyluo already raised for iOS #836 ,  we need a QR Code that exports Vault details, so users can import in web and join airdrop.

Please use the #836 for functionality reference.

And [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=7592-14093&t=lr7S9OUCYrUaHdfT-4) for UI reference, as we need a way to export the Vault information in app.

Therefore change main vault view so it includes the QR share option in top right, as we have pulldown feature to refresh and we don't need refresh button, can be replaced.

The saved QR-code needs name format: Vultisig-{VaultName}-{xyz}.png . `XYZ is last 3 digits of UID`
With the `save or share` button give option to store on device or share directly on other apps/users.

![image](https://github.com/vultisig/vultisig-ios/assets/167348323/2481c2cd-28fa-4992-bae9-d34ab46c5ce5)

**Comment by johnnyluo** [comment]
implemented in #910
