### ISSUE TITLE
[BUG] Gray bar on some screens on Mac

### ISSUE THREAD

**Issue by Rockindash** [vultisig/vultisig-ios#857]
**Describe the bug**
Gray bar appears on top of the view random after some navigation flow.

**To Reproduce**
1. Craete a new Vaulkt on Mac.
2. The gray bar is visible on top of the Home View.
3. After restarting the app it disappears.

**Expected behavior**
The gray bar shouldn't be visible.

**Screenshots**
<img width="907" alt="Screenshot 2024-07-09 at 2 08 02 AM" src="https://github.com/vultisig/vultisig-ios/assets/13535088/ff41db06-2012-42e6-b558-b6e453b906c4">

**Comment by johnnyluo** [comment]
That looks like the tab bar
