### ISSUE TITLE
[BUG] Crash after signing error

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#859]
**Describe the bug**
After sending a USDT transaction, pairing device (iPhone) displayed tx successfully. while macOS showed signing error. TX went thorugh successfully.
After pressing "try again" the app crashed.

**Expected behavior**
Conceive display if TX failed or went through. If error is present the app doesn't crash if pressing the button.

**Screenshots**
![image](https://github.com/vultisig/vultisig-ios/assets/167348323/77a5df51-1503-49ad-99d2-8d969afc6f33)

**Desktop (please complete the following information):**
 - OS: macOS 14.5.
 - Version 37

**Additional context**
Just happened once so far

**Comment by enriquesouza** [comment]
@johnnyluo it is still happening. I am testing it here. So still something related to protobuff. 

<img width="1590" alt="image" src="https://github.com/user-attachments/assets/c5d860f7-4d3e-49f1-b1e5-f63d5b72ecf3">

**Comment by enriquesouza** [comment]
It does not happen when using an iOS physical device and an iOS simulator; it only occurs when using the MAC native and an iOS simulator.

**Comment by enriquesouza** [comment]
I could sign using the MAC OS native and my phone. I belive we have an issue while exporting the QRCode or reading it after exported. 
<img width="999" alt="image" src="https://github.com/user-attachments/assets/068ce17d-a594-4d56-be7d-d459e57b8ebe">

**Comment by enriquesouza** [comment]
https://drive.google.com/file/d/1yBsbm6PDKNRDdueUOQGSYLs3PTOp1oHB/view?usp=share_link

**Comment by realpaaao** [comment]
close not repoducable atm
