### ISSUE TITLE
[BUG] Adding custom token crashes app

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#863]
**Describe the bug**
Adding a custom token results in a crash on macOS app.
After restarting the token got successfully added.

**To Reproduce**
1. add custom token on any chain
2. See error

**Expected behavior**

**Screenshots**
<img width="898" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/167348323/8922ac16-8096-4d5d-a8ba-284123efb036">

**Desktop (please complete the following information):**
 - OS: 14.5
 - Version 37

**Comment by enriquesouza** [comment]
https://github.com/vultisig/vultisig-ios/pull/887/files
