### ISSUE TITLE
[BUG] No possible to select ETH tokens on search

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#873]
**Describe the bug**
When adding a token on ETH over the search function, it doesn't get added to the vault. When adding over the pre-presented list of tokens it is possible

**To Reproduce**
1. Go to "Add Tokens" View
2. Search for token and "save"
3. See error, token doesn't get added

**Expected behavior**
Able to add tokens after search

**Screenshots**

https://github.com/user-attachments/assets/2d10ef43-8976-4328-9639-d697d21d0be4

-iOS version 37

**Additional context**
Could be possible that it only happens when ETh balance in general is 0, as with my swap vault it does not happen

**Comment by enriquesouza** [comment]
<img width="476" alt="image" src="https://github.com/user-attachments/assets/c6f41efb-e2f3-4dce-9592-dfe257559740">
I just tested it now. None of those tokes I know, one i've searched and it worked.
