### ISSUE TITLE
ADD: Camera view on macOS

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#900]
At the moment macOS only allows pairing with imported QR Codes. Please implement Camera View that macOS can scan QR codes.

**Comment by johnnyluo** [comment]
Refer to Exdus wallet

**Comment by Rockindash** [comment]
Since it was taking way to long to implement this feature, I have separated the on-screen scanner and created another ticket for it.
https://github.com/vultisig/vultisig-ios/issues/1052

**Comment by johnnyluo** [comment]
Closing
