### ISSUE TITLE
IMPROVE: Token view

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#908]
Please update the token view for chains according to [figma ](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=1127-13246&t=6dBHHxOIE0VhwdjG-4). To have Value on the right matching main view and add comma seperators for tokens with more than 1,000 tokens to have a clearer display.

![image](https://github.com/user-attachments/assets/72615ea4-666a-4752-aeb8-2b919c50994a)

**Comment by enriquesouza** [comment]
@realpaaao basically what you want is to invert the order, so on the right side the dollar and bellow the amount in tokens?

<img width="693" alt="image" src="https://github.com/user-attachments/assets/490fcf4b-885a-4049-a7ce-09f39e7cdab2">
