### ISSUE TITLE
[BUG]UTXO to EVM token swap not possible

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#921]
**Describe the bug**
Swapping UTXO chains to EVM tokens is not possible. A signing error occurs, possible a protobuf mapping error.

**To Reproduce**
1. swap a UTXO asset to EVM token (e.g. Doge to USDT.AVAX)
2. sign the transaction
3. See error

**Expected behavior**
able to sign tx

**Screenshots**
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/1975c0ce-9c5f-4a96-bc7e-b9ee3ca3b409">

-version 41

**Comment by johnnyluo** [comment]
@realpaaao I think this is for swap initiated from IOS/MacOS , but paired with android ? 
If that is the case , this will be fixed by the following PR in android
https://github.com/vultisig/vultisig-android/pull/614

**Comment by realpaaao** [comment]
@johnnyluo no, also happens for swaps initated from mac/iOS to iOS
