### ISSUE TITLE
blowfish.xyz - SOLANA

### ISSUE THREAD

**Issue by enriquesouza** [vultisig/vultisig-ios#942]

**Comment by enriquesouza** [comment]
@johnnyluo @realpaaao I don't think we will be able to do that in the same way we have done for EVMs. We only get the unsigned transaction after signing the transaction, so it does not work at all. 

https://github.com/trustwallet/wallet-core/issues/3952

I was trying to get it without sending the signatures, but the wallet core transaction compile method only works if we send the signatures. 

So, I also tried to find a manual lib to build a transaction, but they need to be updated in 3/4 years. 

So we have 2 options, verify after signing or ask Blowfish to change. They are not totally open to change but they said they would do it if it is a full blocker.

**Comment by johnnyluo** [comment]
I think this one is implemented
