### ISSUE TITLE
ADD: Buy WEWE Button on Base

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#945]
After implemetation of #872 please implement a visual Button in `Base` `ChainTokenView` to directly swap to $WEWE.

Logic:
When pressing `Buy wewe ` Button, open Swap page where $WEWE is already selected. 
With commit 8aac247 $WEWE is already in the app.

For UI, use [figma](https://www.figma.com/design/puB2fsVpPrBx3Sup7gaa3v/Vultisig-App?node-id=1127-13246&t=5YD6TXm6N3evzBnE-4) design:

![image](https://github.com/user-attachments/assets/7b4f5fc3-1c8a-4379-8848-4145fc6a5a1f)

**Comment by johnnyluo** [comment]
added at #977
