### ISSUE TITLE
[BUG] "nonce too high" error on swap

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#956]
**Describe the bug**
When swapping on EVM the error "nonce too high" get prompted consistently on the initating device

**To Reproduce**
1. Initate a swap
2. See error

**Expected behavior**
Broadcast the tx on all devices consistently.

-v42

**Comment by johnnyluo** [comment]
Can we please show the transaction hash for both Approval and Swap transaction on screen
