### ISSUE TITLE
[BUG] Not able to swap over MAYA

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#972]
When trying to quote a swap over MAYA the error `Swap amount too small` gets prompted.
Even though the chains are cheap and 30$ should be more than sufficient to make a swap.

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/e4849b6c-5346-48f3-9a2b-bbb29545aba5">

**Comment by flypaper0** [comment]
@realpaaao  should be resolved

**Comment by johnnyluo** [comment]
Fixed , Closing
